-- Singapore miles blogs. All WordPress, all standard /feed/ endpoints.
-- Swap these for your region; any RSS or Atom feed works.
INSERT OR IGNORE INTO feeds (url, label, kind) VALUES
  ('https://milelion.com/feed/',             'MileLion',     'rss'),
  ('https://mainlymiles.com/feed/',          'Mainly Miles',  'rss'),
  ('https://blog.seedly.sg/feed/',           'Seedly',        'rss'),
  ('https://www.moneysmart.sg/blog/feed/',   'MoneySmart',    'rss'),
  ('https://milelion.com/category/credit-cards/', 'MileLion cards', 'page'),
  ('https://mainlymiles.com/category/credit-cards/', 'Mainly Miles cards', 'page');


-- Loyalty programmes and the routes between them.
INSERT OR IGNORE INTO programs (key, name, kind, unit, expiry_months) VALUES
  ('citi_ty',     'Citi ThankYou Points',    'bank',    'points', 60),
  ('citi_miles',  'Citi Miles',              'bank',    'miles',  NULL),
  ('dbs_points',  'DBS Points',              'bank',    'points', 36),
  ('uob_uni',     'UOB UNI$',                'bank',    'UNI$',   24),
  ('ocbc_dollar', 'OCBC$',                   'bank',    'OCBC$',  NULL),
  ('ocbc_90n',    'OCBC 90N Miles',          'bank',    'miles',  NULL),
  ('hsbc_points', 'HSBC Points',             'bank',    'points', 37),
  ('scb_360',     'SC 360 Rewards',          'bank',    'points', NULL),
  ('amex_mr',     'Amex Membership Rewards', 'bank',    'points', NULL),
  ('krisflyer',   'KrisFlyer',               'airline', 'miles',  36),
  ('asia_miles',  'Asia Miles',              'airline', 'miles',  NULL),
  ('heymax',      'HeyMax Max Miles',        'bank',    'miles',  NULL),
  ('eva_air',     'EVA Infinity MileageLands','airline','miles',  NULL),
  ('ana',         'ANA Mileage Club',        'airline', 'miles',  36),
  ('qatar',       'Qatar Privilege Club',    'airline', 'Avios',  NULL),
  ('british_aw',  'British Airways Club',    'airline', 'Avios',  NULL),
  ('emirates',    'Emirates Skywards',       'airline', 'miles',  NULL),
  ('qantas',      'Qantas Frequent Flyer',   'airline', 'points', NULL),
  ('united',      'United MileagePlus',      'airline', 'miles',  NULL),
  ('turkish',     'Turkish Miles&Smiles',    'airline', 'miles',  NULL);

-- expiry_months is left NULL wherever the rule is not something to assert from
-- memory. It is only a default for new batches; the date on each batch is what
-- actually drives the expiry warnings, so set that when you record a balance.

-- The RATIOS below are corroborated across several public summaries published
-- between Nov 2025 and Sep 2026. The FEES AND MINIMUMS are not: sources
-- disagree, and they move (UOB raised its fee in Dec 2025, HSBC reworked its
-- ratio in Jan 2025). Every row is therefore seeded with verified_at NULL, and
-- the weekly rates review reports it as unverified until you check it against
-- your own bank and run /verified. Treat the fees as placeholders.
INSERT OR IGNORE INTO conversions
  (id, from_program, to_program, from_units, to_units, fee_cents, min_block, block_increment, route, note) VALUES
  (1,  'citi_ty',     'krisflyer',  25000, 10000, 2725, 25000, 25000, 'direct', 'fee and min unverified'),
  (2,  'citi_ty',     'krisflyer',  10000,  4000,    0, 10000, 10000, 'Kris+',  'fee-free route, verify it still exists'),
  (3,  'citi_miles',  'krisflyer',  10000, 10000, 2725, 10000,  1000, 'direct', '1 to 1, fee and min unverified'),
  (4,  'dbs_points',  'krisflyer',   5000, 10000, 2725,  5000,  5000, 'direct', '1 point = 2 miles, fee unverified'),
  (5,  'dbs_points',  'asia_miles',  5000, 10000, 2725,  5000,  5000, 'direct', 'fee and min unverified'),
  (6,  'uob_uni',     'krisflyer',   5000, 10000, 2700,  2500,  2500, 'direct', 'fee rose Dec 2025, verify'),
  (7,  'uob_uni',     'asia_miles',  5000, 10000, 2700,  2500,  2500, 'direct', 'fee and min unverified'),
  (8,  'ocbc_dollar', 'krisflyer',  25000, 10000, 2725,  2500,  2500, 'direct', '5 to 2, fee and min unverified'),
  (9,  'ocbc_90n',    'krisflyer',  10000, 10000, 2725, 10000,  1000, 'direct', '1 to 1, fee and min unverified'),
  (10, 'hsbc_points', 'krisflyer',  30000, 10000,    0, 30000, 30000, 'direct', 'often fee-free, verify for your card'),
  (11, 'hsbc_points', 'asia_miles', 25000, 10000,    0, 25000, 25000, 'direct', 'fee and min unverified'),
  (12, 'scb_360',     'krisflyer',  25000, 10000, 2725, 25000, 25000, 'direct', 'ratio and fee unverified'),
  (13, 'amex_mr',     'krisflyer',   4500,  2000,    0,  4500,  4500, 'direct', 'often free and instant, verify');

-- Merchant category codes. The codes and descriptions are the ISO standard and
-- stable; the category column is this app's own mapping onto earn_rules.
-- Every MCC in ISO 18245, with the descriptions published at
-- https://www.check-mcc.sg/mcc (fetched 2026-09-14). The `category` column
-- is this app's own mapping onto earn_rules and is NOT part of the standard:
-- it is what the earn engine matches a rule against, so correct it here if
-- your card's terms group a code differently.
--
-- Codes 3000-3999 are individual airlines, hotel chains and car rental
-- agencies. They are real — a hotel charge often posts as 3509 rather than
-- 7011 — but there are 595 of them, so the Codes tab hides them by default.
-- Every MCC in ISO 18245. Descriptions are Citibank's, from the Merchant
-- Category Codes manual it publishes for commercial cards; codes it does not
-- list keep the wording from https://www.check-mcc.sg/mcc and carry
-- verified = 0, so the app can say which is which.
--
-- The `category` column is this app's own mapping onto earn_rules and is NOT
-- part of the standard: it is what the earn engine matches a rule against,
-- so correct it here if your card's terms group a code differently.
--
-- Codes 3000-3999 are individual airlines, hotel chains and car rental
-- agencies. They are real — a hotel charge often posts as 3509 rather than
-- 7011 — but there are 596 of them, so the Codes tab hides them by default.
--
-- Descriptions are refreshed on every /seed; categories are left alone, so an
-- edit of your own survives.
INSERT INTO mcc_codes (code, description, category, verified) VALUES
  ('0742','Veterinary Services','health',1),
  ('0763','Agricultural Cooperatives','other',1),
  ('0780','Horticultural and Landscaping Services','home',1),
  ('1520','General Contractors–Residential and Commercial','home',1),
  ('1711','Air Conditioning, Heating and Plumbing Contractors','home',1),
  ('1731','Electrical Contractors','home',1),
  ('1740','Insulation, Masonry, Plastering, Stonework and Tile Setting Contractors','home',0),
  ('1750','Carpentry Contractors','home',1),
  ('1761','Roofing and Siding, Sheet Metal Work Contractors','home',1),
  ('1771','Concrete Work Contractors','home',1),
  ('1799','Contractors, Special Trade Contractors–not elsewhere classified','home',1),
  ('2741','Miscellaneous Publishing and Printing','other',1),
  ('2791','Typesetting, Plate Making and Related Services','other',1),
  ('2842','Sanitation, Polishing and Specialty Cleaning Preparations','home',1),
  ('3000','United Airlines','travel',1),
  ('3001','American Airlines','travel',1),
  ('3002','Pan American','travel',1),
  ('3003','Eurofly','travel',1),
  ('3004','Dragon Airlines','travel',1),
  ('3005','British Airways','travel',1),
  ('3006','Japan Air Lines','travel',1),
  ('3007','Air France','travel',1),
  ('3008','Lufthansa German Airlines','travel',1),
  ('3009','Air Canada','travel',1),
  ('3010','Royal Dutch Airlines (KLM Airlines)','travel',1),
  ('3011','Aeroflot','travel',1),
  ('3012','Qantas','travel',1),
  ('3013','Alitalia','travel',1),
  ('3014','Saudi Arabian Airlines','travel',1),
  ('3015','Swiss International Air Lines','travel',1),
  ('3016','Scandinavian Airline System (SAS)','travel',1),
  ('3017','South African Airways','travel',1),
  ('3018','Varig','travel',1),
  ('3019','Germanwings','travel',1),
  ('3020','Air India','travel',1),
  ('3021','Air Algerie','travel',1),
  ('3022','Philippine Airlines','travel',1),
  ('3023','Mexicana','travel',1),
  ('3024','Pakistan International','travel',1),
  ('3025','Air New Zealand Ltd. International','travel',1),
  ('3026','Emirates Airlines','travel',1),
  ('3027','Union De Transports Aeriens (UTA/interair)','travel',1),
  ('3028','Air Malta','travel',1),
  ('3029','SN Brussels Airlines','travel',1),
  ('3030','Aerolineas Argentinas','travel',1),
  ('3031','Olympic Airways','travel',1),
  ('3032','El Al','travel',1),
  ('3033','Ansett Airlines','travel',1),
  ('3034','Etihadair','travel',1),
  ('3035','TAP Air Portugal (TAP)','travel',1),
  ('3036','Viacao Aerea Sao Pãulo (VASP)','travel',1),
  ('3037','Egyptair','travel',1),
  ('3038','Kuwait Airways','travel',1),
  ('3039','Avianca','travel',1),
  ('3040','Gulf Air (Bahrain)','travel',1),
  ('3041','Balkan-Bulgarian Airlines','travel',1),
  ('3042','Finnair','travel',1),
  ('3043','Aer Lingus','travel',1),
  ('3044','Air Lanka','travel',1),
  ('3045','Nigeria Airways','travel',1),
  ('3046','Cruzeiro Do Sul','travel',1),
  ('3047','Turk Hava Yollari','travel',1),
  ('3048','Royal Air Maroc','travel',1),
  ('3049','Tunis Air','travel',1),
  ('3050','Icelandair','travel',1),
  ('3051','Austrian Airlines','travel',1),
  ('3052','LAN Airlines','travel',1),
  ('3053','Aviacion Y Comercio (AVIACO)','travel',1),
  ('3054','Linea Aerea Del Cobre (LADECO)','travel',1),
  ('3055','Lloyd Aero Boliviano (LAB)','travel',1),
  ('3056','Jet Airways','travel',1),
  ('3057','Virgin America','travel',1),
  ('3058','Delta','travel',1),
  ('3059','DBA Airline','travel',1),
  ('3060','Northwest Airlines','travel',1),
  ('3061','Continental','travel',1),
  ('3062','Hapag-Lloyd Express','travel',1),
  ('3063','US Airways','travel',1),
  ('3064','Adria Airways','travel',1),
  ('3065','Airinter','travel',1),
  ('3066','Southwest Airlines','travel',1),
  ('3067','Vanguard Airlines','travel',1),
  ('3068','Air Astana','travel',1),
  ('3069','Sun Country Airlines','travel',1),
  ('3071','Air British Columbia','travel',1),
  ('3072','Cebu Pacific Airlines','travel',1),
  ('3075','Singapore Airlines','travel',1),
  ('3076','Aeromexico','travel',1),
  ('3077','Thai Airways','travel',1),
  ('3078','China Airlines','travel',1),
  ('3079','Jetstar Airways','travel',1),
  ('3081','NordAir','travel',1),
  ('3082','Korean Airlines','travel',1),
  ('3083','Air Afrique','travel',1),
  ('3084','Eva Airways','travel',1),
  ('3085','Midwest Express Airlines','travel',1),
  ('3086','Carnival Airlines','travel',1),
  ('3087','Metro Airlines','travel',1),
  ('3088','Croatia Air','travel',1),
  ('3089','Transaero','travel',1),
  ('3090','Uni Airways Corporation','travel',1),
  ('3094','Zambia Airways','travel',1),
  ('3096','Air Zimbabwe Corp','travel',1),
  ('3097','Spanair','travel',1),
  ('3098','Asiana Airlines','travel',1),
  ('3099','Cathay Pacific','travel',1),
  ('3100','Malaysian Airline System','travel',1),
  ('3102','Iberia','travel',1),
  ('3103','Garuda','travel',1),
  ('3106','Braathens S.A.F.E.','travel',1),
  ('3110','Wings Airways','travel',1),
  ('3111','British Midland','travel',1),
  ('3112','Windward Island','travel',1),
  ('3115','Tower Air','travel',1),
  ('3117','Venezolana International De Aviacion','travel',1),
  ('3118','Valley Airlines','travel',1),
  ('3125','Tan Sahsa','travel',1),
  ('3126','Talair PTY Ltd.','travel',1),
  ('3127','Taca International','travel',1),
  ('3129','Surinam Airways','travel',1),
  ('3130','Sunworld International','travel',1),
  ('3131','VLM Airlines','travel',1),
  ('3132','Frontier Airlines','travel',1),
  ('3133','Sunbelt Airlines','travel',1),
  ('3135','Sudan Airways','travel',1),
  ('3136','Qatar Airways','travel',1),
  ('3137','Singleton','travel',1),
  ('3138','Simmons Airlines','travel',1),
  ('3143','Scenic Airlines','travel',1),
  ('3144','Virgin Atlantic','travel',1),
  ('3145','San Juan','travel',1),
  ('3146','Luxair','travel',1),
  ('3148','Air Littoral S.A.','travel',1),
  ('3151','Air Zaire','travel',1),
  ('3154','Princeville','travel',1),
  ('3156','Go Fly Ltd.','travel',1),
  ('3159','Provincetown-Boston Airways','travel',1),
  ('3161','All Nipon Airways','travel',1),
  ('3164','Norontair','travel',1),
  ('3165','New York Helicopter','travel',1),
  ('3167','Aero Continente','travel',1),
  ('3170','Mount Cook','travel',1),
  ('3171','Canadian Airlines International','travel',1),
  ('3172','Nationair','travel',1),
  ('3174','JetBlue Airways','travel',0),
  ('3175','Middle East Air','travel',1),
  ('3176','Metroflight Airlines','travel',1),
  ('3177','AirTran Airways','travel',1),
  ('3178','Mesa Air','travel',1),
  ('3180','Westjet Airlines','travel',1),
  ('3181','Malev','travel',1),
  ('3182','LOT (Polish Airlines)','travel',1),
  ('3183','Oman Air','travel',1),
  ('3184','LIAT','travel',1),
  ('3185','Linea Aeropostal Venezolana (LAV)','travel',1),
  ('3186','Lineas Aereas Paraguayas (LAP)','travel',1),
  ('3187','LACSA (Costa Rica)','travel',1),
  ('3188','Virgin Express','travel',1),
  ('3190','Jugoslav Air','travel',1),
  ('3191','Island Airlines','travel',1),
  ('3193','Indian Airlines','travel',1),
  ('3196','Hawaiian Air','travel',1),
  ('3197','Havasu Airlines','travel',1),
  ('3200','Guyana Airways','travel',1),
  ('3203','Golden Pacific Air','travel',1),
  ('3204','Freedom Airlines','travel',1),
  ('3206','China Eastern Airlines','travel',1),
  ('3211','Norwegian Air Shuttle','travel',1),
  ('3212','Dominicana De Aviacion','travel',1),
  ('3213','Malmo Aviation','travel',1),
  ('3215','Dan Air Services','travel',1),
  ('3216','Cumberland Airlines','travel',1),
  ('3217','Ceskoslovenske Aerolinie (CSA)','travel',1),
  ('3218','Crown Air','travel',1),
  ('3219','Compania Panamena De Aviacion (COPA)','travel',1),
  ('3220','Compania Faucett','travel',1),
  ('3221','Transportes Aeros Militares','travel',1),
  ('3222','Command Airways','travel',1),
  ('3223','Comair','travel',1),
  ('3226','Skyways','travel',1),
  ('3228','Cayman Airways','travel',1),
  ('3229','SAETA (Sociedad Ecuatorianos De Transportes Aereos)','travel',1),
  ('3231','SAHSA (Servicio Aero De Honduras)','travel',1),
  ('3233','Capitol Air','travel',1),
  ('3234','Caribbean Airlines','travel',1),
  ('3235','Brockway Air','travel',1),
  ('3236','Air Arabia Airline','travel',1),
  ('3238','Bemidji Aviation','travel',1),
  ('3239','Bar Harbor Airlines','dining',1),
  ('3240','Bahamasair','travel',1),
  ('3241','Aviateca','travel',1),
  ('3242','Avensa','travel',1),
  ('3243','Austrian Air Service','travel',1),
  ('3245','Easyjet Air','travel',1),
  ('3246','Ryanair','travel',1),
  ('3247','Gol Airlines','travel',1),
  ('3248','Tam Airlines','travel',1),
  ('3251','Aloha Airlines','travel',1),
  ('3252','Antilean Airlines (ALM)','travel',1),
  ('3253','America West','travel',1),
  ('3254','U.S. Air Shuttle','travel',1),
  ('3256','Alaska Airlines Inc.','travel',1),
  ('3259','American Trans Air','travel',1),
  ('3260','Spirit Airlines','travel',1),
  ('3261','Air China','travel',1),
  ('3262','Reno Air','travel',1),
  ('3263','Aero Servicio Carabobo','travel',1),
  ('3266','Air Seychelles','travel',1),
  ('3267','Air Panama International','travel',1),
  ('3273','Rica Hotels','travel',1),
  ('3274','Inter Nor Hotels','travel',1),
  ('3280','Air Jamaica','travel',1),
  ('3281','Air Djibouti','travel',1),
  ('3282','Air Djibouti','travel',1),
  ('3284','Aero Virgin Islands','travel',1),
  ('3285','Aero Peru','travel',1),
  ('3286','Aero Nicaraguensis','travel',1),
  ('3287','Aero Coach Aviation','travel',1),
  ('3292','Cyprus Airways','travel',1),
  ('3293','Ecuatoriana','travel',1),
  ('3294','Ethiopian Airlines','travel',1),
  ('3295','Kenya Airways','travel',1),
  ('3296','Air Berlin','travel',1),
  ('3297','Tarom Romanian Air Transport','travel',1),
  ('3298','Air Mauritius','travel',1),
  ('3299','Wideroes Flyveselskap','travel',1),
  ('3351','Affiliated Auto Rental','travel',1),
  ('3352','American International','travel',1),
  ('3353','Brooks Rent-A-Car','travel',1),
  ('3354','Action Auto Rental','travel',1),
  ('3355','Sixt Car Rental','travel',1),
  ('3357','Hertz','travel',1),
  ('3359','Payless Car Rental','travel',1),
  ('3360','Snappy Car Rental','travel',1),
  ('3361','Airways','travel',1),
  ('3362','Altra Auto Rental','travel',1),
  ('3364','Agency Rent-A-Car','travel',1),
  ('3366','Budget Rent-A-Car','travel',1),
  ('3368','Holiday Rent-A-Car','travel',1),
  ('3370','Rent-A-Wreck','travel',1),
  ('3374','Accent Rent-A-Car','travel',1),
  ('3376','Ajax Rent-A-Car','travel',1),
  ('3380','Triangle Rent-A-Car','travel',1),
  ('3381','Europcar','travel',1),
  ('3385','Tropical Rent-A-Car','travel',1),
  ('3386','Showcase Rental Cars','travel',1),
  ('3387','Alamo Rent-A-Car','travel',1),
  ('3388','Merchants Rent-A-Car','travel',1),
  ('3389','Avis Rent-A-Car','travel',1),
  ('3390','Dollar Rent-A-Car','travel',1),
  ('3391','Europe By Car','travel',1),
  ('3393','National Car Rental','travel',1),
  ('3394','Kemwell Group','travel',1),
  ('3395','Thrifty Car Rental','travel',1),
  ('3396','Tilden Rent-A-Car','travel',1),
  ('3398','Econo-Car Rent-A-Car','travel',1),
  ('3400','Auto Host Rental Cars','travel',1),
  ('3405','Enterprise Rent-A-Car','travel',1),
  ('3409','General Rent-A-Car','travel',1),
  ('3412','A1 Rent-A-Car','travel',1),
  ('3414','Godfrey National','travel',1),
  ('3420','Ansa International','travel',1),
  ('3421','Allstate','travel',1),
  ('3423','AVCAR','travel',1),
  ('3425','Automate','travel',1),
  ('3427','Avon Rent-A-Car','travel',1),
  ('3428','Carey','travel',1),
  ('3429','Insurance Rent-A-Car','insurance',1),
  ('3430','Major Rent-A-Car','travel',1),
  ('3431','Replacement Rent-A-Car','travel',1),
  ('3432','Reserve Rent-A-Car','travel',1),
  ('3433','Ugly Duckling Rent-A-Car','travel',1),
  ('3434','USA Rent-A-Car','travel',1),
  ('3435','Value Rent-A-Car','travel',1),
  ('3436','Autohansa','travel',1),
  ('3437','Cite','travel',1),
  ('3438','Interent','travel',1),
  ('3439','Milleville','travel',1),
  ('3441','Advantage Rent A Car','travel',1),
  ('3500','Lodging, individual hotel chain','travel',0),
  ('3501','Holiday Inns','travel',1),
  ('3502','Best Western','travel',1),
  ('3503','Sheraton','travel',1),
  ('3504','Hilton','travel',1),
  ('3505','Trusthouse Forte','travel',1),
  ('3506','Golden Tulip','travel',1),
  ('3507','Friendship Inns International','travel',1),
  ('3508','Quality International','travel',1),
  ('3509','Marriott','travel',1),
  ('3510','Days Inns Of America','travel',1),
  ('3511','Arabella Hotels','travel',1),
  ('3512','Intercontinental','travel',1),
  ('3513','Westin Hotels','travel',1),
  ('3514','Amerisuites','travel',1),
  ('3515','Rodeway Inns International','travel',1),
  ('3516','La Quinta Motor Inns','travel',1),
  ('3517','Americana Hotels Corporation','travel',1),
  ('3518','Sol Hotels','travel',1),
  ('3519','PLM/ETAP International','travel',1),
  ('3520','Meridien','travel',1),
  ('3521','Crest Hotels','travel',1),
  ('3522','Tokyo Group','travel',1),
  ('3523','Peninsula Hotels','travel',1),
  ('3524','Welcomgroup','travel',1),
  ('3525','Dunfey Hotels','travel',1),
  ('3526','Prince Hotels','travel',1),
  ('3527','Downtowner Passport','travel',1),
  ('3528','Thunderbird/Red Lion','travel',1),
  ('3529','CP (Canadian Pacific)','travel',1),
  ('3530','Renaissance Hotels','travel',1),
  ('3531','Kauai Coconut Beach Resort','travel',1),
  ('3532','Royal Kona Resort','travel',1),
  ('3533','Park Inn by Radisson','travel',1),
  ('3534','Southern Pacific Hotel','travel',1),
  ('3535','Hilton International','travel',1),
  ('3536','AMFAC Hotels','travel',1),
  ('3537','Ana Hotels','travel',1),
  ('3538','Concorde Hotels','travel',1),
  ('3539','Summerfield Suites Hotel','travel',1),
  ('3540','Iberotel','travel',1),
  ('3541','Hotel Okura','travel',1),
  ('3542','Royal Hotels','travel',1),
  ('3543','Four Seasons','travel',1),
  ('3544','Cigahotels','travel',1),
  ('3545','Shangri-La International','travel',1),
  ('3546','Hotel Sierra','travel',1),
  ('3547','Breakers Resort','travel',1),
  ('3548','Hotels Melia','travel',1),
  ('3549','Auberge Des Governeurs','travel',1),
  ('3550','Regal 8 Inns','travel',1),
  ('3551','Mirage Hotel and Casino','travel',1),
  ('3552','Coast Hotels','travel',1),
  ('3553','Parks Inns International','travel',1),
  ('3554','Pinehurst Resort','travel',1),
  ('3555','Treasure Island Hotel and Casino','travel',1),
  ('3556','Barton Creek Resort','travel',1),
  ('3557','Manhattan East Suite Hotels','travel',1),
  ('3558','Jolly Hotels','travel',1),
  ('3559','Candlewood Suites','travel',1),
  ('3560','Aladdin Resort and Casino','travel',1),
  ('3561','Golden Nugget','travel',1),
  ('3562','Comfort Hotel International','travel',1),
  ('3563','Journeys End Motels','travel',1),
  ('3564','Sams Town Hotel and Casino','travel',1),
  ('3565','Relax Inns','travel',1),
  ('3566','Garden Place Hotel','travel',1),
  ('3567','Soho Grand Hotel','travel',1),
  ('3568','Ladbroke Hotels','travel',1),
  ('3569','Tribeca Grand Hotel','travel',1),
  ('3570','Grand Met Forum Hotels','travel',1),
  ('3571','Grand Wailea Resort','travel',1),
  ('3572','Miyako Hotel/Kintetsu','travel',1),
  ('3573','Sandman Hotels','travel',1),
  ('3574','Venture Inn','travel',1),
  ('3575','Vagabond Hotels','travel',1),
  ('3576','La Quinta Resort','travel',1),
  ('3577','Mandarin International','travel',1),
  ('3578','Frankenmuth Bavarian','travel',1),
  ('3579','Hotel Mercure','travel',1),
  ('3580','Hotel Del Coronado','travel',1),
  ('3581','Delta Hotels','travel',1),
  ('3582','California Hotel and Casino','travel',1),
  ('3583','Radisson BLU','travel',1),
  ('3584','Princess Hotels International','travel',1),
  ('3585','Hungar Hotels','travel',1),
  ('3586','Sokos Hotel','travel',1),
  ('3587','Doral Hotels','travel',1),
  ('3588','Helmsley Hotels','travel',1),
  ('3589','Doral Golf Resort','travel',1),
  ('3590','Fairmont Hotels Corporation','travel',1),
  ('3591','Sonesta International Hotels','travel',1),
  ('3592','Omni International','travel',1),
  ('3593','Cunard Hotels','travel',1),
  ('3594','Arizona Biltmore','travel',1),
  ('3595','Hospitality Inns','health',1),
  ('3596','Wynn Las Vegas','travel',1),
  ('3597','Riverside Resort and Casino','travel',1),
  ('3598','Regent Hotels','travel',1),
  ('3599','Pannonia Hotels','travel',1),
  ('3600','Saddlebrook Resort– Tampa','travel',1),
  ('3601','Tradewinds Resort','travel',1),
  ('3602','Hudson Hotel','travel',1),
  ('3603','Noahs Hotel (Melbourne)','travel',1),
  ('3604','Hilton Garden Inn','travel',1),
  ('3605','Jurys Doyle Hotel Group','travel',1),
  ('3606','Jefferson Hotel','travel',1),
  ('3607','Fontainebleau Resort','travel',1),
  ('3608','Gaylord Opryland','travel',1),
  ('3609','Gaylord Palms','travel',1),
  ('3610','Gaylord Texan','travel',1),
  ('3611','C MON INN','travel',1),
  ('3612','Moevenpick','travel',1),
  ('3613','Microtel Inn and Suites','travel',1),
  ('3614','AmericInn','travel',1),
  ('3615','Travelodge Motels','travel',1),
  ('3616','Hermitage Hotels','travel',1),
  ('3617','America’s Best Value Inn','travel',1),
  ('3618','Great Wolf','travel',1),
  ('3619','Aloft','travel',1),
  ('3620','Binions Horseshoe Club','shopping',1),
  ('3621','Extended Stay','travel',1),
  ('3622','Merlin Hotel (Perth)','travel',1),
  ('3623','Dorint Hotels','travel',1),
  ('3624','Lady Luck Hotel and Casino','travel',1),
  ('3625','Hotel Universal','travel',1),
  ('3626','Studio Plus','travel',1),
  ('3627','Extended Stay America','travel',1),
  ('3628','Excalibur Hotel and Casino','travel',1),
  ('3629','Dan Hotels','travel',1),
  ('3630','Extended Stay Deluxe','travel',1),
  ('3631','Sleep Inn','travel',1),
  ('3632','The Phoenician','travel',1),
  ('3633','Rank Hotels','travel',1),
  ('3634','Swissotel','travel',1),
  ('3635','Reso Hotels','travel',1),
  ('3636','Sarova Hotels','travel',1),
  ('3637','Ramada Inns','travel',1),
  ('3638','Howard Johnson','travel',1),
  ('3639','Mount Charlotte Hotels','travel',1),
  ('3640','Hyatt Hotels/International','travel',1),
  ('3641','Sofitel Hotels','travel',1),
  ('3642','Novotel Sieh (Accor)','travel',1),
  ('3643','Steigenberger','travel',1),
  ('3644','Econo-Travel Motor Hotel','travel',1),
  ('3645','Queens Moat Houses','travel',1),
  ('3646','Swallow Hotels','travel',1),
  ('3647','Grupo Hotels HUSA SA','travel',1),
  ('3648','De Vere Hotels','travel',1),
  ('3649','Radisson','travel',1),
  ('3650','Red Roof Inns','travel',1),
  ('3651','Imperial London Hotels','travel',1),
  ('3652','Embassy Hotels','travel',1),
  ('3653','Penta Hotels','travel',1),
  ('3654','Loews Hotels','travel',1),
  ('3655','Scandic Hotels','travel',1),
  ('3656','Sara Hotels','travel',1),
  ('3657','Oberoi Hotels','travel',1),
  ('3658','New Otani Hotels','travel',1),
  ('3659','Taj Hotels Intl','travel',1),
  ('3660','Knights Inn','travel',1),
  ('3661','Metropole Hotels','travel',1),
  ('3662','Circus Circus Hotel and Casino','travel',1),
  ('3663','Hoteles El Presidente','travel',1),
  ('3664','Flag Inns','travel',1),
  ('3665','Hampton Inns','travel',1),
  ('3666','Stakis Hotels','travel',1),
  ('3667','Luxor Hotel and Casino','travel',1),
  ('3668','Maritim','travel',1),
  ('3669','Eldorado Hotel and Casino','travel',1),
  ('3670','Arcade','entertainment',1),
  ('3671','Arctia','travel',1),
  ('3672','Campanile','travel',1),
  ('3673','Ibusz Hotels','travel',1),
  ('3674','Rantasipi Hotels','travel',1),
  ('3675','Interhotel Cedok','travel',1),
  ('3676','Monte Carlo Hotel and Casino','travel',1),
  ('3677','Climat De France','travel',1),
  ('3678','Cumulus Hotels','travel',1),
  ('3679','Silver Legacy Hotel and Casino','travel',1),
  ('3680','Hoteis Othan','travel',1),
  ('3681','Adams Mark','travel',1),
  ('3682','Sahara Hotel and Casino','travel',1),
  ('3683','Bradbury Suites','travel',1),
  ('3684','Budget Host Inns','travel',1),
  ('3685','Budgetel','travel',1),
  ('3686','Suisse Chalet','travel',1),
  ('3687','Clarion Hotel','travel',1),
  ('3688','Compri Hotel','travel',1),
  ('3689','Consort','travel',1),
  ('3690','Courtyard by Marriott','travel',1),
  ('3691','Dillon Inn','travel',1),
  ('3692','Doubletree','travel',1),
  ('3693','Drury Inn','travel',1),
  ('3694','Economy Inns Of America','travel',1),
  ('3695','Embassy Suites','travel',1),
  ('3696','Excel Inn','travel',1),
  ('3697','Fairfield Hotel','travel',1),
  ('3698','Harley Hotel','travel',1),
  ('3699','Midway Motor Lodge','travel',1),
  ('3700','Motel 6','travel',1),
  ('3701','La Mansion Del Rio','travel',1),
  ('3702','Registry Hotels','travel',1),
  ('3703','Residence Inn','travel',1),
  ('3704','Royce Hotel','travel',1),
  ('3705','Sandman Inn','travel',1),
  ('3706','Shilo Inn','travel',1),
  ('3707','Shoneys Inn','travel',1),
  ('3708','Virgin River Hotel and Casino','travel',1),
  ('3709','Super 8 Motel','travel',1),
  ('3710','Ritz-Carlton','travel',1),
  ('3711','Flag Inns (Australia)','travel',1),
  ('3712','Buffalo Bills Hotel and Casino','travel',1),
  ('3713','Quality Pacific Hotel','travel',1),
  ('3714','Four Seasons (Australia)','travel',1),
  ('3715','Fairfield Inn','travel',1),
  ('3716','Carlton Hotels','travel',1),
  ('3717','City Lodge Hotels','travel',1),
  ('3718','Karos Hotels','travel',1),
  ('3719','Protea Hotels','travel',1),
  ('3720','Southern Sun Hotels','travel',1),
  ('3721','Conrad Hotels','travel',1),
  ('3722','Wyndham','travel',1),
  ('3723','Rica Hotels','travel',1),
  ('3724','Inter Nor Hotels','travel',1),
  ('3725','Sea Pines Resort','travel',1),
  ('3726','Rio Suites','travel',1),
  ('3727','Broadmoor Hotel','travel',1),
  ('3728','Ballys Hotel and Casino','travel',1),
  ('3729','John Ascuagas Nugget','travel',1),
  ('3730','MGM Grand Hotel','travel',1),
  ('3731','Harrah’s Hotels and Casinos','travel',1),
  ('3732','Opryland Hotel','travel',1),
  ('3733','Boca Raton Resort','travel',1),
  ('3734','Harvey Bristol Hotels','travel',1),
  ('3735','Masters Economy Inns','travel',1),
  ('3736','Colorado Belle Edgewater Resort','travel',1),
  ('3737','Riviera Hotel and Casino','travel',1),
  ('3738','Tropicana Resort and Casino','travel',1),
  ('3739','Woodside Hotels and Resorts','travel',1),
  ('3740','Towneplace Suites 32','travel',0),
  ('3741','Millennium Broadway Hotel','travel',1),
  ('3742','Club Med','travel',1),
  ('3743','Biltmore Hotel and Suites','travel',0),
  ('3744','Carefree Resorts','travel',0),
  ('3745','St. Regis Hotel','travel',1),
  ('3746','The Eliot Hotel','travel',0),
  ('3747','Club Corporation/Club Resorts','travel',1),
  ('3748','Wellesley Inns','travel',1),
  ('3749','Beverly Hills Hotel','travel',1),
  ('3750','Crowne Plaza Hotels','travel',1),
  ('3751','Homewood Suites','travel',1),
  ('3752','Peabody Hotels','travel',1),
  ('3753','Greenbriar Resorts','travel',1),
  ('3754','Amelia Island Plantation','travel',1),
  ('3755','Homestead','travel',1),
  ('3757','Canyon Ranch','travel',1),
  ('3758','Kahala Mandarin Oriental Hotel','travel',1),
  ('3759','Orchid At Mauna Lai','travel',1),
  ('3760','Halekulani Hotel/Waikiki Parc','travel',1),
  ('3761','Primadonna Hotel and Casino','travel',1),
  ('3762','Whiskey Pete’s Hotel and Casino','travel',1),
  ('3763','Chateau Elan Winery and Resort','travel',1),
  ('3764','Beau Rivage Hotel and Casino','travel',1),
  ('3765','Bellagio','travel',1),
  ('3766','Fremont Hotel and Casino','travel',1),
  ('3767','Main Street Station Hotel and Casino','travel',1),
  ('3768','Silver Star Hotel and Casino','travel',1),
  ('3769','Stratosphere Hotel and Casino','travel',1),
  ('3770','Springhill Suites','travel',1),
  ('3771','Caesars Hotel and Casino','travel',1),
  ('3772','Nemacolin Woodlands','travel',1),
  ('3773','Venetian Resort Hotel and Casino','travel',1),
  ('3774','New York-New York Hotel and Casino','travel',1),
  ('3775','Sands Resort','travel',1),
  ('3776','Nevele Grande Resort and Country Club','travel',1),
  ('3777','Mandalay Bay Resort','travel',1),
  ('3778','Four Points Hotels','travel',1),
  ('3779','W Hotels','travel',1),
  ('3780','Disneyland Resorts','travel',1),
  ('3781','Patricia Grand Resort Hotels','travel',1),
  ('3782','Rosen Hotel and Resorts','travel',1),
  ('3783','Town and Country Resort and Convention Center','travel',1),
  ('3784','First Hospitality Hotels','health',1),
  ('3785','Outrigger Hotels and Resorts','travel',1),
  ('3786','Ohana Hotels of Hawaii','travel',1),
  ('3787','Caribe Royal Resort Suite and Villas','travel',1),
  ('3788','Ala Moana Hotel','travel',1),
  ('3789','Smugglers Notch Resort','travel',1),
  ('3790','Raffles Hotels','travel',1),
  ('3791','Staybridge Suites','travel',1),
  ('3792','Claridge Casino Hotel','travel',1),
  ('3793','The Flamingo Hotels','travel',1),
  ('3794','Grand Casino Hotels','travel',1),
  ('3795','Paris Las Vegas Hotel','travel',1),
  ('3796','Peppermill Hotel Casino','travel',1),
  ('3797','Atlantic City Hilton','travel',1),
  ('3798','Embassy Vacation Resort','travel',1),
  ('3799','Hale Koa Hotel','travel',1),
  ('3800','Homestead Suites','travel',1),
  ('3801','Wilderness Hotel and Resort','travel',1),
  ('3802','The Palace Hotel','travel',1),
  ('3803','The Wigwam Golf Resort and Spa','health',1),
  ('3804','The Diplomat Country Club and Spa','health',1),
  ('3805','The Atlantic','travel',1),
  ('3806','Princeville Resort','travel',1),
  ('3807','Element','travel',1),
  ('3808','LXR (Luxury Resorts)','travel',1),
  ('3809','Settle Inn','travel',1),
  ('3810','La Costa Resort','travel',1),
  ('3811','Premier Travel Inns','travel',1),
  ('3812','Hyatt Place','travel',1),
  ('3813','Hotel Indigo','travel',1),
  ('3814','The Roosevelt Hotel NY','travel',1),
  ('3815','Nickelodeon Family Suites by Holiday Inn','travel',1),
  ('3816','Home2Suites','travel',1),
  ('3817','Affinia','travel',1),
  ('3818','Mainstay Suites','travel',1),
  ('3819','Oxford Suites','travel',1),
  ('3820','Jumeirah Essex House','travel',1),
  ('3821','Caribe Royal','travel',1),
  ('3822','Crossland','travel',1),
  ('3823','Grand Sierra Resort','travel',1),
  ('3824','Aria','travel',1),
  ('3825','Vdara','travel',1),
  ('3826','Autograph','travel',1),
  ('3827','Galt House','travel',1),
  ('3828','Cosmopolitan of Las Vegas','travel',1),
  ('3829','Country Inn By Carlson','travel',1),
  ('3830','Park Plaza Hotel','travel',1),
  ('3831','Waldorf','travel',1),
  ('3837','Hoshino Resorts','travel',0),
  ('4011','Railroads–Freight','transport',1),
  ('4111','Transportation–Suburban and Local Commuter Passenger , including Ferries','transport',1),
  ('4112','Passenger Railways','transport',1),
  ('4119','Ambulance Services','health',1),
  ('4121','Taxicabs and Limousines','transport',1),
  ('4131','Bus Lines','transport',1),
  ('4214','Motor Freight Carriers,Trucking–Local/Long Distance, Moving and Storage Companies, Local Delivery','other',1),
  ('4215','Courier Services–Air and Ground, Freight ForwardersV','shopping',1),
  ('4225','Public Warehousing–Farm Products, Refrigerated Goods, Household Goods Storage','other',1),
  ('4411','Cruise Lines','travel',1),
  ('4457','Boat Leases and Boat Rentals','travel',1),
  ('4468','Marinas, Marine Service/Supplies','travel',1),
  ('4511','Air Carriers, Airlines–not elsewhere classified','travel',1),
  ('4582','Airports, Airport Terminals, Flying Fields','travel',1),
  ('4722','Travel Agencies and Tour Operators','travel',1),
  ('4723','Package Tour Operators (Germany Only)','travel',1),
  ('4761','Telemarketing of Travel Related Services and Vitamins','online',1),
  ('4784','Bridge and Road Fees, Tolls','transport',1),
  ('4789','Transportation Services Not Elsewhere Classified','transport',1),
  ('4812','Telecommunication Equipment Including Telephone Sales','utilities',1),
  ('4813','Key-Entry Telecom Merchant providing single local and long-distance phone calls using a central access number in a non-face-to-face environment using key entry Telecommunication Services including but not limited to prepaid phone services and recurring phone services','utilities',1),
  ('4814','Telecommunication Services including but not limited to prepaid phone services and recurring phone services','utilities',1),
  ('4816','Computer Network/Information Services','utilities',1),
  ('4821','Telegraph Services','utilities',1),
  ('4829','Wire Transfer Money Orders (V, D, G, X) Money Transfer (M)','financial',1),
  ('4899','Cable, Satellite, and Other Pay Television and Radio Services','utilities',1),
  ('4900','Utilities–Electric, Gas, Heating Oil, Sanitary, Water','utilities',1),
  ('5013','Motor Vehicle Supplies and New Parts','other',1),
  ('5021','Office and Commercial Furniture','shopping',1),
  ('5039','Construction Materials Not Elsewhere Classified','other',1),
  ('5044','Office, Photographic, Photocopy and Microfilm Equipment','other',1),
  ('5045','Computers, Computer Peripheral Equipment, Software','other',1),
  ('5046','Commercial Equipment Not Elsewhere Classified','other',1),
  ('5047','Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies','health',1),
  ('5051','Metal Service Centers and Offices','other',1),
  ('5065','Electrical Parts and Equipment','other',1),
  ('5072','Hardware Equipment and Supplies','shopping',1),
  ('5074','Plumbing and Heating Equipment','home',0),
  ('5085','Industrial Supplies Not Elsewhere Classified','other',1),
  ('5094','Precious Stones and Metals, Watches and Jewelry','shopping',1),
  ('5099','Durable Goods Not Elsewhere Classified','other',1),
  ('5111','Stationery, Office Supplies, Printing and Writing Paper','shopping',1),
  ('5122','Drugs, Drug Proprietors and Druggists Sundries','health',1),
  ('5131','Piece Goods, Notions, and Other Dry Goods','other',1),
  ('5137','Men’s, Women’s and Children’s Uniforms and Commercial Clothing','shopping',1),
  ('5139','Commercial Footware','other',1),
  ('5169','Chemicals and Allied Products Not Elsewhere Classified','other',1),
  ('5172','Petroleum and Petroleum Products','fuel',1),
  ('5192','Books, Periodicals and Newspapers','shopping',1),
  ('5193','Florists Supplies, Nursery Stock and Flowers','shopping',1),
  ('5198','Paints, Varnishes and Supplies','shopping',1),
  ('5199','Non-Durable Goods Not Elsewhere Classified','other',1),
  ('5200','Home Supply Warehouse Stores','shopping',1),
  ('5211','Building Materials, Lumber Stores','shopping',1),
  ('5231','Glass, Paint, Wallpaper Stores','shopping',1),
  ('5251','Hardware Stores','shopping',1),
  ('5261','Lawn and Garden Supply Stores','shopping',1),
  ('5262','Marketplaces','online',0),
  ('5271','Mobile Home Dealers','shopping',1),
  ('5299','Warehouse Club Gas','fuel',1),
  ('5300','Wholesale Clubs','shopping',1),
  ('5309','Duty Free Stores','shopping',1),
  ('5310','Discount Stores','shopping',1),
  ('5311','Department Stores','shopping',1),
  ('5331','Variety Stores','shopping',1),
  ('5399','Miscellaneous General Merchandise Stores','shopping',1),
  ('5411','Grocery Stores, Supermarkets','groceries',1),
  ('5422','Freezer and Locker Meat Provisioners','groceries',1),
  ('5441','Candy, Nut and Confectionery Stores','groceries',1),
  ('5451','Dairy Products Stores','groceries',1),
  ('5462','Bakeries','dining',1),
  ('5499','Miscellaneous Food Stores–Convenience Stores, Markets, Specialty Stores, and Vending Machines','groceries',1),
  ('5511','Automobile and Truck Dealers–Sales, Service, Repairs, Parts and Leasing','transport',1),
  ('5521','Automobile and Truck Dealers–(Used Only)–Sales','shopping',1),
  ('5531','Auto and Home Supply Outlets','transport',0),
  ('5532','Automotive Tire Stores','transport',1),
  ('5533','Automotive Parts and Accessories Stores','transport',1),
  ('5541','Service Stations (With or Without Ancillary Services)','fuel',1),
  ('5542','Fuel Dispenser , Automated','fuel',1),
  ('5551','Boat Dealers','shopping',1),
  ('5552','Electric Vehicle (EV) Charging services','fuel',0),
  ('5561','Camper Dealers, Recreational and Utility Trailers','shopping',1),
  ('5571','Motorcycle Shops and Dealers','transport',1),
  ('5592','Motor Home Dealers','shopping',1),
  ('5598','Snowmobile Dealers','shopping',1),
  ('5599','Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers–Not Elsewhere Classified','shopping',1),
  ('5611','Men’s and Boys’ Clothing and Accessories Stores','shopping',1),
  ('5621','Women’s Ready to Wear Stores','shopping',1),
  ('5631','Women’s Accessory and Specialty Stores','shopping',1),
  ('5641','Children’s and Infants’ Wear Stores','shopping',1),
  ('5651','Family Clothing Stores','shopping',1),
  ('5655','Sports Apparel, and Riding Apparel Stores','shopping',1),
  ('5661','Shoe Stores','shopping',1),
  ('5681','Furriers and Fur Shops','shopping',1),
  ('5691','Men’s and Women’s Clothing Stores','shopping',1),
  ('5697','Alterations, Mending, Seamstresses, Tailors','shopping',1),
  ('5698','Wig and Toupee Shops','shopping',1),
  ('5699','Accessory and Apparel Stores–Miscellaneous','shopping',1),
  ('5712','Equipment, Furniture and Home Furnishings Stores (except Appliances)','shopping',1),
  ('5713','Floor Covering Stores','shopping',1),
  ('5714','Drapery, Upholstery and Window Coverings Stores','shopping',1),
  ('5715','Alcoholic Beverage Wholesalers','shopping',0),
  ('5718','Fireplace, Fireplace Screens and Accessories Stores','shopping',1),
  ('5719','Miscellaneous House Furnishing Specialty Shops','shopping',1),
  ('5722','Household Appliance Stores','shopping',1),
  ('5732','Electronics Sales','shopping',1),
  ('5733','Music Stores–Musical Instruments, Pianos and Sheet Music','shopping',1),
  ('5734','Computer Software Stores','shopping',1),
  ('5735','Record Shops','shopping',1),
  ('5811','Caterers','dining',1),
  ('5812','Eating Places and Restaurants','dining',1),
  ('5813','Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns–Drinking Places (Alcoholic Beverages)','dining',1),
  ('5814','Fast Food Restaurants','dining',1),
  ('5815','Digital Goods: Books, Movies, Music','online',1),
  ('5816','Digital Goods: Games','online',1),
  ('5817','Digital Goods: Applications (Excludes Games)','online',1),
  ('5818','Digital Goods — Multi-category','online',1),
  ('5912','Drug Stores and Pharmacies','health',1),
  ('5921','Package Stores–Beer , Wine and Liquor','groceries',1),
  ('5931','Second Hand Stores, Used Merchandise Stores','shopping',1),
  ('5932','Antique Shops–Sales, Repairs and Restoration Services','shopping',1),
  ('5933','Pawn Shops','other',1),
  ('5935','Wrecking and Salvage Yards','other',1),
  ('5937','Antique Reproduction Stores','shopping',1),
  ('5940','Bicycle Shops–Sales and Service','shopping',1),
  ('5941','Sporting Goods Stores','shopping',1),
  ('5942','Book Stores','shopping',1),
  ('5943','Office, School Supply and Stationery Stores','shopping',1),
  ('5944','Clock, Jewelry, Watch and Silverware Stores','shopping',1),
  ('5945','Game, Toy and Hobby Shops','shopping',1),
  ('5946','Camera and Photographic Supply Stores','shopping',1),
  ('5947','Card, Gift, Novelty and Souvenir Shops','shopping',1),
  ('5948','Leather Goods and Luggage Stores','shopping',1),
  ('5949','Fabric, Needlework, Piece Goods and Sewing Stores','shopping',1),
  ('5950','Crystal and Glassware Stores','shopping',1),
  ('5960','Direct Marketing Insurance Services','insurance',1),
  ('5961','Mail Order Houses Including Catalog Order Stores','shopping',1),
  ('5962','Direct Marketing– Travel Related Arrangement Services','online',1),
  ('5963','Door-to-Door Sales','online',1),
  ('5964','Direct Marketing–Catalog Merchants','online',1),
  ('5965','Direct Marketing–Combination Catalog and Retail Merchant','online',1),
  ('5966','Direct Marketing–Outbound Telemarketing MerchantsV','online',1),
  ('5967','Direct Marketing–Inbound Telemarketing Merchants','online',1),
  ('5968','Direct Marketing–Continuity/Subscription Merchants','online',1),
  ('5969','Direct Marketing–Other Direct Marketers–Not Elsewhere Classified','online',1),
  ('5970','Artist Supply Stores, Craft Shops','shopping',1),
  ('5971','Art Dealers and Galleries','shopping',1),
  ('5972','Stamp and Coin Stores–Philatelic and Numismatic Supplies','shopping',1),
  ('5973','Religious Goods Stores','charity',1),
  ('5974','Rubber Stamp Store','shopping',0),
  ('5975','Hearing Aids–Sales, Service, Supply Stores','shopping',1),
  ('5976','Orthopedic Goods–Artificial Limb Stores','shopping',1),
  ('5977','Cosmetic Stores','shopping',1),
  ('5978','Typewriter Stores–Rentals, Sales, Service','shopping',1),
  ('5983','Fuel Dealers–Coal, Fuel Oil, Liquefied Petroleum, Wood','fuel',1),
  ('5992','Florists','shopping',1),
  ('5993','Cigar Stores and Stands','shopping',1),
  ('5994','News Dealers and Newsstands','shopping',1),
  ('5995','Pet Shops, Pet Food and Supplies','shopping',1),
  ('5996','Swimming Pools–Sales and Supplies','home',1),
  ('5997','Electric Razor Stores–Sales and Service','shopping',1),
  ('5998','Tent and Awning Shops','shopping',1),
  ('5999','Miscellaneous and Specialty Retail Stores','shopping',1),
  ('6010','Member Financial Institution–Manual Cash Disbursements','financial',1),
  ('6011','Member Financial Institution–Automated Cash Disbursements','financial',1),
  ('6012','Member Financial Institution–Merchandise And Services','financial',1),
  ('6050','Quasi Cash–Member Financial Institution','financial',1),
  ('6051','Non-financial Institutions – Foreign Currency, Money Orders not Wire Transfer and Travelers Cheques','financial',1),
  ('6211','Securities–Brokers and Dealers','financial',1),
  ('6236','Aero Servicio Carabobo','travel',1),
  ('6300','Insurance Sales, Underwriting and Premiums','insurance',1),
  ('6381','Insurance–Premiums','insurance',1),
  ('6399','Insurance, other','insurance',0),
  ('6513','Real Estate Agents and Managers–Rentals','rental',1),
  ('6529','Remote Stored Value Load — Member Financial Institution','financial',1),
  ('6530','Remove Stored Value Load — Merchant','financial',1),
  ('6532','Payment transaction, member financial institution','financial',0),
  ('6533','Payment Transaction — Merchant','financial',0),
  ('6534','Money transfer, member financial institution','financial',0),
  ('6535','Value Purchase–Member Financial Institution','financial',1),
  ('6536','MoneySend Intracountry','financial',1),
  ('6537','MoneySend Intercountry','financial',1),
  ('6538','MoneySend Funding','financial',1),
  ('6539','Funding Transaction (Excluding MoneySend)','financial',1),
  ('6540','POI (Point of Interaction) Funding Transactions (Excluding MoneySend)','financial',1),
  ('6611','Overpayments','financial',1),
  ('6760','Savings Bonds','financial',1),
  ('7011','Lodging–Hotels, Motels, Resorts–not elsewhere classified','travel',1),
  ('7012','Timeshares','travel',1),
  ('7032','Sporting and Recreational Camps','entertainment',1),
  ('7033','Campgrounds and Trailer Parks','travel',1),
  ('7210','Cleaning, Garment and Laundry Services','other',1),
  ('7211','Laundry Services–Family and Commercial','other',1),
  ('7216','Dry Cleaners','other',1),
  ('7217','Carpet and Upholstery Cleaning','home',1),
  ('7221','Photographic Studios','other',1),
  ('7230','Barber and Beauty Shops','health',1),
  ('7251','Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors','home',1),
  ('7261','Funeral Service and Crematories','other',1),
  ('7273','Dating Services','other',1),
  ('7276','Tax Preparation Service','other',1),
  ('7277','Debt, Marriage, Personal–Counseling Services','other',1),
  ('7278','Buying/Shopping Clubs, Services','other',1),
  ('7280','Hospital Patient-Personal Funds Withdrawal','health',1),
  ('7295','Babysitting Services','other',1),
  ('7296','Clothing Rental–Costumes, Uniforms and Formal Wear','other',1),
  ('7297','Massage Parlors','health',1),
  ('7298','Health and Beauty Spas','health',1),
  ('7299','Other Services–Not Elsewhere Classified','health',1),
  ('7311','Advertising Services','other',1),
  ('7321','Consumer Credit Reporting Agencies','financial',1),
  ('7332','Blueprinting and Photocopying Services','other',1),
  ('7333','Commercial Art, Graphics, Photography','other',1),
  ('7338','Quick Copy, Reproduction and Blueprinting Services','other',1),
  ('7339','Stenographic and Secretarial Support Services','other',1),
  ('7342','Exterminating and Disinfecting Services','home',1),
  ('7349','Cleaning and Maintenance, Janitorial Services','home',1),
  ('7361','Employment Agencies and Temporary Help Services','other',1),
  ('7372','Computer Programming, Data Processing and Integrated System Design Services','utilities',1),
  ('7375','Information Retrieval Services','utilities',1),
  ('7379','Computer Maintenance, Repair And Services–Not Elsewhere Classified','utilities',1),
  ('7392','Consulting, Management and Public Relations Services','other',1),
  ('7393','Detective Agencies, Protective Agencies, Security Services including Armored Cars, Guard Dogs','other',1),
  ('7394','Equipment Rental and Leasing Services, Furniture Rental, Tool Rental','other',1),
  ('7395','Photo Developing, Photofinishing Laboratories','other',1),
  ('7399','Business Services Not Elsewhere Classified','other',1),
  ('7512','Automobile Rental Agency–Not Elsewhere Classified','travel',1),
  ('7513','Truck Rental','utilities',1),
  ('7519','Motor Home and Recreational Vehicle Rental','entertainment',1),
  ('7523','Automobile Parking Lots and Garages','transport',1),
  ('7524','Express Payment Service Merchants–Parking Lots and Garages','transport',1),
  ('7531','Automotive Body Repair Shops','transport',1),
  ('7534','Tire Retreading and Repair Shops','transport',1),
  ('7535','Automotive Paint Shops','transport',1),
  ('7538','Automotive Service Shops','transport',1),
  ('7542','Car Washes','transport',1),
  ('7549','Towing Services','transport',1),
  ('7622','Electronic Repair Shops','home',1),
  ('7623','Air Conditioning and Refrigeration Repair Shops','home',1),
  ('7629','Appliance Repair Shops, Electrical and Small','home',1),
  ('7631','Clock, Jewelry and Watch Repair Shops','home',1),
  ('7641','Furniture–Reupholstery, Repair and Refinishing','home',1),
  ('7692','Welding Repair','home',1),
  ('7699','Miscellaneous Repair Shops and Related Services','home',1),
  ('7800','Government Owned Lottery','government',1),
  ('7801','Government-Licensed Casinos (Online or Internet Gambling)','financial',1),
  ('7802','Government-Licensed Horse/Dog Racing','financial',1),
  ('7829','Motion Picture and Video Tape Production and Distribution','entertainment',1),
  ('7832','Motion Picture Theaters','entertainment',1),
  ('7833','Express Payment Service — Motion Picture Theater','entertainment',1),
  ('7841','DVD/Video Tape Rental Stores','shopping',1),
  ('7911','Dance Halls, Schools and Studios','entertainment',1),
  ('7922','Theatrical Producers (Except Motion Pictures), Ticket Agencies','entertainment',1),
  ('7929','Bands, Orchestras and Miscellaneous Entertainers– Not Elsewhere Classified','entertainment',1),
  ('7932','Pool and Billiard Establishments','entertainment',1),
  ('7933','Bowling Alleys','entertainment',1),
  ('7941','Athletic Fields, Commercial Sports, Professional Sports Clubs, Sports Promoters','entertainment',1),
  ('7991','Tourist Attractions and Exhibits','entertainment',1),
  ('7992','Golf Courses, Public','entertainment',1),
  ('7993','Video Amusement Game Supplies','entertainment',1),
  ('7994','Video Game Arcades and Establishments','entertainment',1),
  ('7995','Betting, lottery and casino gaming','financial',1),
  ('7996','Amusement Parks, Carnivals, Circuses, Carnivals, Fortune Tellers','entertainment',1),
  ('7997','Clubs–Country Clubs, Membership (Athletic, Recreation, Sports), Private Golf Courses','entertainment',1),
  ('7998','Aquariums, Dolphinariums, Zoos and Seaquariums','entertainment',1),
  ('7999','Recreation Services–Not Elsewhere Classified','entertainment',1),
  ('8011','Doctors–not elsewhere classified','health',1),
  ('8021','Dentists and Orthodontists','health',1),
  ('8031','Osteopathic Physicians','health',1),
  ('8041','Chiropractors','health',1),
  ('8042','Optometrists and Ophthalmologists','health',1),
  ('8043','Opticians, Optical Goods and Eyeglasses','health',1),
  ('8044','Optical Goods and Eyeglasses','health',1),
  ('8049','Chiropodists, Podiatrists','health',1),
  ('8050','Nursing and Personal Care Facilities','health',1),
  ('8062','Hospitals','health',1),
  ('8071','Dental and Medical Laboratories','health',1),
  ('8099','Health Practitioners, Medical Services–Not Elsewhere Classified','health',1),
  ('8111','Attorneys, Legal Services','government',1),
  ('8211','Schools, Elementary and Secondary','education',1),
  ('8220','Colleges, Universities, Professional Schools and Junior Colleges','education',1),
  ('8241','Schools, Correspondence','education',1),
  ('8244','Schools, Business and Secretarial','education',1),
  ('8249','Schools, Trade and Vocational','education',1),
  ('8299','Schools And Educational Services–Not Elsewhere Classified','education',1),
  ('8351','Child Care Services','education',1),
  ('8398','Organizations, Charitable and Social Service','charity',1),
  ('8641','Associations–Civic, Social and Fraternal','charity',1),
  ('8651','Organizations, Political','charity',1),
  ('8661','Organizations, Religious','charity',1),
  ('8675','Automobile Associations','charity',1),
  ('8699','Organizations, Membership–Not Elsewhere Classified','charity',1),
  ('8734','Testing Laboratories (Non-Medical)','health',1),
  ('8743','Testing Laboratories (Non-Medical)','health',0),
  ('8911','Architectural, Engineering and Surveying Services','other',1),
  ('8931','Accounting, Auditing and Bookkeeping Services','shopping',1),
  ('8999','Professional Services–Not Elsewhere Classified','government',1),
  ('9034','I-Purchasing Pilot','other',1),
  ('9211','Court Costs Including Alimony and Child Support','government',1),
  ('9222','Fines','government',1),
  ('9223','Bail and Bond Payments','government',1),
  ('9311','Tax Payments','government',1),
  ('9399','Government Services–Not Elsewhere Classified','government',1),
  ('9401','I-Purchasing Pilot','government',1),
  ('9402','Postal Services–Government Only','government',1),
  ('9405','Intra-Government Purchases–Government Only','government',1),
  ('9700','Automated Referral Service','government',1),
  ('9701','Visa Credential Server','government',1),
  ('9702','GCAS Emergency Services','government',1),
  ('9751','UK Supermarkets, Electronic Hot File','groceries',1),
  ('9752','UK Petrol Stations, Electronic Hot File','fuel',1),
  ('9754','Gambling-Horse, Dog Racing, State Lottery','financial',1),
  ('9950','Intra-Company Purchases','government',1)
ON CONFLICT(code) DO UPDATE SET description = excluded.description, verified = excluded.verified;

-- MCCs that most Singapore cards exclude from bonus earning. Seeded as a
-- starting point ONLY: exclusion lists are per-card and change, so check your
-- own terms and edit. card_id null means it applies to every card.
INSERT OR IGNORE INTO exclusions (id, card_id, mcc, reason, source) VALUES
  (1,  NULL, '6012', 'Financial services are excluded by most issuers', 'seed'),
  (2,  NULL, '6051', 'Quasi-cash and top-ups are excluded by most issuers', 'seed'),
  (3,  NULL, '4829', 'Money transfers are excluded by most issuers', 'seed'),
  (4,  NULL, '6300', 'Insurance premiums are commonly excluded', 'seed'),
  (5,  NULL, '9311', 'Tax payments are commonly excluded', 'seed'),
  (6,  NULL, '9399', 'Government services are commonly excluded', 'seed'),
  (7,  NULL, '9211', 'Court costs and fines are commonly excluded', 'seed'),
  (8,  NULL, '9222', 'Fines are commonly excluded', 'seed'),
  (9,  NULL, '8220', 'Education is commonly excluded', 'seed'),
  (10, NULL, '8211', 'Schools are commonly excluded', 'seed'),
  (11, NULL, '6513', 'Rental payments are commonly excluded', 'seed'),
  (12, NULL, '8398', 'Charitable donations are commonly excluded', 'seed');

-- Likely merchant codes. GUESSES, not facts: the code is set by the acquirer,
-- differs between outlets of the same brand and changes without notice. Confirm
-- one from a posted transaction and the app will trust it over these.
INSERT OR IGNORE INTO merchant_mcc (merchant, mcc, channel, source, confidence) VALUES
  ('din tai fung','5812','offline','seed','guess'),
  ('ntuc fairprice','5411','offline','seed','guess'),
  ('fairprice','5411','offline','seed','guess'),
  ('cold storage','5411','offline','seed','guess'),
  ('sheng siong','5411','offline','seed','guess'),
  ('giant','5411','offline','seed','guess'),
  ('shopee','5262','online','seed','guess'),
  ('lazada','5262','online','seed','guess'),
  ('amazon','5262','online','seed','guess'),
  ('taobao','5262','online','seed','guess'),
  ('grab','4121','online','seed','guess'),
  ('gojek','4121','online','seed','guess'),
  ('comfortdelgro','4121','offline','seed','guess'),
  ('courts','5732','offline','seed','guess'),
  ('harvey norman','5732','offline','seed','guess'),
  ('challenger','5732','offline','seed','guess'),
  ('uniqlo','5651','offline','seed','guess'),
  ('zara','5651','offline','seed','guess'),
  ('decathlon','5941','offline','seed','guess'),
  ('watsons','5912','offline','seed','guess'),
  ('guardian','5912','offline','seed','guess'),
  ('unity','5912','offline','seed','guess'),
  ('singapore airlines','4511','online','seed','guess'),
  ('scoot','4511','online','seed','guess'),
  ('agoda','4722','online','seed','guess'),
  ('booking.com','4722','online','seed','guess'),
  ('expedia','4722','online','seed','guess'),
  ('klook','4722','online','seed','guess'),
  ('netflix','4899','online','seed','guess'),
  ('spotify','4899','online','seed','guess'),
  ('disney+','4899','online','seed','guess'),
  ('singtel','4814','online','seed','guess'),
  ('starhub','4814','online','seed','guess'),
  ('m1','4814','online','seed','guess'),
  ('sp group','4900','online','seed','guess'),
  ('shell','5541','offline','seed','guess'),
  ('esso','5541','offline','seed','guess'),
  ('caltex','5541','offline','seed','guess'),
  ('spc','5541','offline','seed','guess'),
  ('golden village','7832','online','seed','guess'),
  ('cathay cineplexes','7832','offline','seed','guess'),
  ('starbucks','5814','offline','seed','guess'),
  ('mcdonald''s','5814','offline','seed','guess'),
  ('toast box','5814','offline','seed','guess'),
  ('ya kun','5814','offline','seed','guess'),
  ('kopitiam','5814','offline','seed','guess');
