-- Singapore miles blogs. All WordPress, all standard /feed/ endpoints.
-- Swap these for your region; any RSS or Atom feed works.
INSERT OR IGNORE INTO feeds (url, label, kind) VALUES
  ('https://milelion.com/feed/',             'MileLion',     'rss'),
  ('https://mainlymiles.com/feed/',          'Mainly Miles',  'rss'),
  ('https://blog.seedly.sg/feed/',           'Seedly',        'rss'),
  ('https://www.moneysmart.sg/blog/feed/',   'MoneySmart',    'rss'),
  ('https://milelion.com/category/credit-cards/', 'MileLion cards', 'page'),
  ('https://mainlymiles.com/category/credit-cards/', 'Mainly Miles cards', 'page');


-- Loyalty programmes and the routes between them.
INSERT OR IGNORE INTO programs (key, name, kind, unit, expiry_months) VALUES
  ('citi_ty',     'Citi ThankYou Points',    'bank',    'points', 60),
  ('citi_miles',  'Citi Miles',              'bank',    'miles',  NULL),
  ('dbs_points',  'DBS Points',              'bank',    'points', 36),
  ('uob_uni',     'UOB UNI$',                'bank',    'UNI$',   24),
  ('ocbc_dollar', 'OCBC$',                   'bank',    'OCBC$',  NULL),
  ('ocbc_90n',    'OCBC 90N Miles',          'bank',    'miles',  NULL),
  ('hsbc_points', 'HSBC Points',             'bank',    'points', 37),
  ('scb_360',     'SC 360 Rewards',          'bank',    'points', NULL),
  ('amex_mr',     'Amex Membership Rewards', 'bank',    'points', NULL),
  ('krisflyer',   'KrisFlyer',               'airline', 'miles',  36),
  ('asia_miles',  'Asia Miles',              'airline', 'miles',  NULL),
  ('heymax',      'HeyMax Max Miles',        'bank',    'miles',  NULL),
  ('eva_air',     'EVA Infinity MileageLands','airline','miles',  NULL),
  ('ana',         'ANA Mileage Club',        'airline', 'miles',  36),
  ('qatar',       'Qatar Privilege Club',    'airline', 'Avios',  NULL),
  ('british_aw',  'British Airways Club',    'airline', 'Avios',  NULL),
  ('emirates',    'Emirates Skywards',       'airline', 'miles',  NULL),
  ('qantas',      'Qantas Frequent Flyer',   'airline', 'points', NULL),
  ('united',      'United MileagePlus',      'airline', 'miles',  NULL),
  ('turkish',     'Turkish Miles&Smiles',    'airline', 'miles',  NULL);

-- expiry_months is left NULL wherever the rule is not something to assert from
-- memory. It is only a default for new batches; the date on each batch is what
-- actually drives the expiry warnings, so set that when you record a balance.

-- The RATIOS below are corroborated across several public summaries published
-- between Nov 2025 and Sep 2026. The FEES AND MINIMUMS are not: sources
-- disagree, and they move (UOB raised its fee in Dec 2025, HSBC reworked its
-- ratio in Jan 2025). Every row is therefore seeded with verified_at NULL, and
-- the weekly rates review reports it as unverified until you check it against
-- your own bank and run /verified. Treat the fees as placeholders.
INSERT OR IGNORE INTO conversions
  (id, from_program, to_program, from_units, to_units, fee_cents, min_block, block_increment, route, note) VALUES
  (1,  'citi_ty',     'krisflyer',  25000, 10000, 2725, 25000, 25000, 'direct', 'fee and min unverified'),
  (2,  'citi_ty',     'krisflyer',  10000,  4000,    0, 10000, 10000, 'Kris+',  'fee-free route, verify it still exists'),
  (3,  'citi_miles',  'krisflyer',  10000, 10000, 2725, 10000,  1000, 'direct', '1 to 1, fee and min unverified'),
  (4,  'dbs_points',  'krisflyer',   5000, 10000, 2725,  5000,  5000, 'direct', '1 point = 2 miles, fee unverified'),
  (5,  'dbs_points',  'asia_miles',  5000, 10000, 2725,  5000,  5000, 'direct', 'fee and min unverified'),
  (6,  'uob_uni',     'krisflyer',   5000, 10000, 2700,  2500,  2500, 'direct', 'fee rose Dec 2025, verify'),
  (7,  'uob_uni',     'asia_miles',  5000, 10000, 2700,  2500,  2500, 'direct', 'fee and min unverified'),
  (8,  'ocbc_dollar', 'krisflyer',  25000, 10000, 2725,  2500,  2500, 'direct', '5 to 2, fee and min unverified'),
  (9,  'ocbc_90n',    'krisflyer',  10000, 10000, 2725, 10000,  1000, 'direct', '1 to 1, fee and min unverified'),
  (10, 'hsbc_points', 'krisflyer',  30000, 10000,    0, 30000, 30000, 'direct', 'often fee-free, verify for your card'),
  (11, 'hsbc_points', 'asia_miles', 25000, 10000,    0, 25000, 25000, 'direct', 'fee and min unverified'),
  (12, 'scb_360',     'krisflyer',  25000, 10000, 2725, 25000, 25000, 'direct', 'ratio and fee unverified'),
  (13, 'amex_mr',     'krisflyer',   4500,  2000,    0,  4500,  4500, 'direct', 'often free and instant, verify');

-- Merchant category codes. The codes and descriptions are the ISO standard and
-- stable; the category column is this app's own mapping onto earn_rules.
-- Every MCC in ISO 18245, with the descriptions published at
-- https://www.check-mcc.sg/mcc (fetched 2026-09-14). The `category` column
-- is this app's own mapping onto earn_rules and is NOT part of the standard:
-- it is what the earn engine matches a rule against, so correct it here if
-- your card's terms group a code differently.
--
-- Codes 3000-3999 are individual airlines, hotel chains and car rental
-- agencies. They are real — a hotel charge often posts as 3509 rather than
-- 7011 — but there are 595 of them, so the Codes tab hides them by default.
INSERT OR IGNORE INTO mcc_codes (code, description, category) VALUES
  ('0742','Veterinary Services','health'),
  ('0763','Agricultural Co-operatives','other'),
  ('0780','Horticultural Services, Landscaping Services','home'),
  ('1520','General Contractors - Residential and Commercial','home'),
  ('1711','Air Conditioning, Heating and Plumbing Contractors','home'),
  ('1731','Electrical Contractors','home'),
  ('1740','Insulation, Masonry, Plastering, Stonework and Tile Setting Contractors','home'),
  ('1750','Carpentry Contractors','home'),
  ('1761','Roofing and Siding, Sheet Metal Work Contractors','home'),
  ('1771','Concrete Work Contractors','home'),
  ('1799','Contractors – Special Trade, Not Elsewhere Classified','home'),
  ('2741','Miscellaneous Publishing and Printing','other'),
  ('2791','Typesetting, Plate Making and Related Services','other'),
  ('2842','Sanitation, Polishing and Specialty Cleaning Preparations','home'),
  ('3000','United Airlines','travel'),
  ('3001','American Airlines','travel'),
  ('3002','Pan American','travel'),
  ('3003','Eurofly','travel'),
  ('3004','Dragon Airlines','travel'),
  ('3005','British Airways','travel'),
  ('3006','Japan Airlines','travel'),
  ('3007','Air France','travel'),
  ('3008','Lufthansa','travel'),
  ('3009','Air Canada','travel'),
  ('3010','KLM Royal Dutch Airlines','travel'),
  ('3011','Aeorflot','travel'),
  ('3012','Quantas','travel'),
  ('3013','Alitalia','travel'),
  ('3014','Saudia Arabian Airlines','travel'),
  ('3015','Swiss Air','travel'),
  ('3016','SAS','travel'),
  ('3017','South African Airways','travel'),
  ('3018','Varig VARIG','travel'),
  ('3019','Germanwings GRMNWNGSAIR','travel'),
  ('3020','Air India','travel'),
  ('3021','Air Algerie','travel'),
  ('3022','Philippine Airlines','travel'),
  ('3023','Mexicana MEXICANA','travel'),
  ('3024','Pakistan International','travel'),
  ('3025','Air New Zealand','travel'),
  ('3026','Emirates Airlines','travel'),
  ('3027','Union De Transports Aeriens (UTA/interair)','travel'),
  ('3028','Air Malta','travel'),
  ('3029','SN Brussels Airlines','travel'),
  ('3030','Aerolineas Argentinas','travel'),
  ('3031','Olympic Airways','travel'),
  ('3032','El Al','travel'),
  ('3033','Ansett Airlines','travel'),
  ('3034','Etihad Airways','travel'),
  ('3035','TAP Air Portugal (TAP)','travel'),
  ('3036','Viacao Aerea Sao Pãulo (VASP)','travel'),
  ('3037','Egyptair SWISSINTAIR (V) SWISS (M) SAS SAA AIRWAYS (V) SAFRICAN (M) AIR-INDIA (V) AIR-INDI (M) AIR ALGERIE (V) AIRALGER (M) PAKISTAN AIR (V) PAKISTAN (M) UTA AIRLINE (V) UTAAIR (M) AIR MALTA (V) AIRMALTA (M) SNBRSSLSAIR (V) SNBRU AIR (M) AERO ARGENT (V) AERO ARG (M) OLYMPIC AIR (V) OLYMPICA (M) EL AL ANSETT AIR (V) ANSETT (M) ETIHADAIR TAP AIR (V) TAP (M) VASP AIR (V) VASP (M) EGYPTAIR 16','travel'),
  ('3038','Kuwait Airways','travel'),
  ('3039','Avianca AVIANCA','travel'),
  ('3040','Gulf Air (Bahrain) GULF AIR','travel'),
  ('3041','Balkan-Bulgarian Airlines','travel'),
  ('3042','Finnair','travel'),
  ('3043','Aer Lingus','travel'),
  ('3044','Air Lanka','travel'),
  ('3045','Nigeria Airways','travel'),
  ('3046','Cruzeiro Do Sul','travel'),
  ('3047','Turk Hava Yollari','travel'),
  ('3048','Royal Air Maroc','travel'),
  ('3049','Tunis Air','travel'),
  ('3050','Icelandair','travel'),
  ('3051','Austrian Airlines','travel'),
  ('3052','Lanchile','travel'),
  ('3053','Aviacion Y Comercio (AVIACO)','travel'),
  ('3054','Linea Aerea Del Cobre (LADECO)','travel'),
  ('3055','Lloyd Aero Boliviano (LAB)','travel'),
  ('3056','Quebecaire','travel'),
  ('3057','Virgin America VIR AMER','travel'),
  ('3058','Delta','travel'),
  ('3059','DBA Airline DBA AIR','travel'),
  ('3060','Northwest Airlines NWA AIR KUWAIT AIR (V) KUWAIT (M) BALKAN AIR (V) BALKAN (M) FINNAIR AER LINGUS (V) AERLING (M) AIR LANKA NIGERIA AIR (V) NIGERIA (M) CRUZIERO AIR (V) CRUZIERO (M) THY AIRLINE (V) THY (M) AIR MAROC (V) AIRMARO (M) TUNIS AIR (V) TUNIS AI (M) ICELANDAIR (V) ICELANDA (M) AUSTRIAN AIR (V) AUSTRIAN (M) LAN AIR AVIACO AIR (V) AVIACO (M) LADECO AIR (V) LADECO (M) LAB AIR (V) LAB (M) DELTA AIR (V) DELTA (M) 17','travel'),
  ('3061','Continental','travel'),
  ('3062','Hapag-Lloyd Express','travel'),
  ('3063','US Airways','travel'),
  ('3064','Adria Airways ADRIA AIR','travel'),
  ('3065','Airinter AIRINTER','travel'),
  ('3066','Southwest','travel'),
  ('3067','Vanguard Airlines','travel'),
  ('3068','Air Astana','travel'),
  ('3069','Sun Country Airlines','travel'),
  ('3071','Air British Columbia','travel'),
  ('3072','Cebu Pacific','travel'),
  ('3075','Singapore Airlines','travel'),
  ('3076','Aeromexico','travel'),
  ('3077','Thai Airways','travel'),
  ('3078','China Airlines','travel'),
  ('3079','Jetstar Airways','travel'),
  ('3081','NordAir','travel'),
  ('3082','Korean Airlines','travel'),
  ('3083','Air Afrique','travel'),
  ('3084','Eva Airlines','travel'),
  ('3085','Midwest Express Airlines','travel'),
  ('3086','Carnival Airlines','travel'),
  ('3087','Metro Airlines','travel'),
  ('3088','Croatia Air','travel'),
  ('3089','Transaero TRANSAERO','travel'),
  ('3090','Uni Airways Corporation UNIAIR','travel'),
  ('3094','Zambia Airways','travel'),
  ('3096','Air Zimbabwe Corp','travel'),
  ('3097','Spanair','travel'),
  ('3098','Asiana Airlines','travel'),
  ('3099','Cathay Pacific','travel'),
  ('3100','Malaysia Airlines','travel'),
  ('3102','Iberia','travel'),
  ('3103','Garuda','travel'),
  ('3106','Braathens S.A.F.E.','travel'),
  ('3110','Wings Airways','travel'),
  ('3111','British Midland','travel'),
  ('3112','Windward Island','travel'),
  ('3115','Tower Air TOWERAIR','travel'),
  ('3117','Venezolana International De Aviacion VIASA','travel'),
  ('3118','Valley Airlines VALLEY AIR AIR AFRIQUE (V) AIR AFRIQ (M) EVA AIR MIDWEST EXP (V) MIDWEST (M) CARNIVAL AIR METRO AIR (V) METROAI (M) CROATIA AIR (V) CROATIA (M) ZAMBIA AIR (V) ZAMBIA A (M) AIR ZIMBABWE (V) AIRZIMBA (M) SPANAIR ASIANA AIR (V) ASIANA (M) CATHAYPACAIR (V) CATHAYPA (M) MALAY AIR (V) MALAY AI (M) IBERIA AIR (V) IBERIA (M) GARUDA AIR (V) GARUDA (M) BRAATHENS (V) BRAATHEN (M) WINGS AIR BRMIDLANDAIR (V) BRITISH M (M) WINDWRDISAIR (V) WINDWARD (M) 19','travel'),
  ('3125','Tan Sahsa TAN AIR','travel'),
  ('3126','Talair PTY Ltd. TALAIR','travel'),
  ('3127','Taca International','travel'),
  ('3129','Surinam Airways','travel'),
  ('3130','Sunworld International','travel'),
  ('3131','VLM Airlines','travel'),
  ('3132','Frontier Airlines','travel'),
  ('3133','Sunbelt Airlines SUNBELT AIR','travel'),
  ('3135','Sudan Airways SUDAN AIR','travel'),
  ('3136','Qatar Airways','travel'),
  ('3137','Singleton SINGLETONAIR','travel'),
  ('3138','Simmons Airlines SIMMONS AIR','travel'),
  ('3143','Scenic Airlines SCENIC AIR','travel'),
  ('3144','Virgin Atlantic','travel'),
  ('3145','San Juan SAN JUAN AIR','travel'),
  ('3146','Luxair LUXAIR','travel'),
  ('3148','Air Littoral S.A.','travel'),
  ('3151','Air Zaire','travel'),
  ('3154','Princeville PRINCVLLEAIR','travel'),
  ('3156','Go Fly Ltd. GOFLY','travel'),
  ('3159','Provincetown-Boston Airways','travel'),
  ('3161','All Nippon Airways','travel'),
  ('3164','Norontair','travel'),
  ('3165','New York Helicopter','travel'),
  ('3167','Aero Continente','travel'),
  ('3170','Mount Cook TACAINTL AIR (V) TACA INT (M) SURINAM AIR (V) SURINAM (M) SUNWORLD AIR (V) SUNWORLD (M) VLM AIR (V) VLM (M) FRONTIER AIR (V) FRONTIER (M) VIRGINATLAIR (V) VIR ATL (M) AIRLITTORAL (V) LITTORAL (M) AIR ZAIRE (V) AIRZAIRE (M) PBA AIRLINE (V) PBA (M) ANA AIR (V) ANAAIR (M) NORONTAIR (V) NORONTAI (M) NY HELI AEROCONTINEN (V) AERO CONT (M) MT COOK AIR 20','travel'),
  ('3171','Canadian Airlines International','travel'),
  ('3172','Nationair','travel'),
  ('3174','JetBlue Airways','travel'),
  ('3175','Middle East Air','travel'),
  ('3176','Metroflight Airlines','travel'),
  ('3177','AirTran Airways','travel'),
  ('3178','Mesa Air','travel'),
  ('3180','Westjet Airlines','travel'),
  ('3181','Malev','travel'),
  ('3182','LOT (Polish Airlines)','travel'),
  ('3183','Oman Air','travel'),
  ('3184','LIAT','travel'),
  ('3185','Linea Aeropostal Venezolana (LAV)','travel'),
  ('3186','Lineas Aereas Paraguayas (LAP)','travel'),
  ('3187','LACSA (Costa Rica)','travel'),
  ('3188','Virgin Express','travel'),
  ('3190','Jugoslav Air','travel'),
  ('3191','Island Airlines','travel'),
  ('3193','Indian Airlines','travel'),
  ('3196','Hawaiian Air Required Abbreviation (Payment Brand) CANADIAN AIR (V) CANADIAN (M) NATIONAIR (V) NATIONAI (M) JETBLUE MIDEAST AIR (V) MIDEASTA (M) METROFLT AIR AIRTRANAIR (V) AIRTRAN A (M) MESA AIR WESTJETAIR (V) WESTJET (M) MALEV AIR (V) MALEV (M) LOT AIR (V) LOT (M) OMANAIR (V) OMAN AIR (M) LIAT AIRLINE (V) LIAT (M) LAV AIR (V) LAV (M) LAP AIR (V) LAP (M) LACSA AIR (V) LACSA (M) VIRGINEXPAIR (V) VIR EXP (M) JUGOSLAV AIR (V) JUGOSLAV (M) ISLAND AIR (V) ISLANDAI (M) INDIAN AIR (V) INDIAN A (M) HAWAIIAN AIR (V) HAWAIIAN (M) 21','travel'),
  ('3197','Havasu Airlines','travel'),
  ('3200','Guyana Airways','travel'),
  ('3203','Golden Pacific Air','travel'),
  ('3204','Freedom Airlines','travel'),
  ('3206','China Eastern Airlines','travel'),
  ('3211','Norwegian Air Shuttle','travel'),
  ('3212','Dominicana De Aviacion','travel'),
  ('3213','Malmo Aviation','travel'),
  ('3215','Dan Air Services DANAIRSERV','travel'),
  ('3216','Cumberland Airlines CUMBERLNDAIR','travel'),
  ('3217','Ceskoslovenske Aerolinie (CSA)','travel'),
  ('3218','Crown Air','travel'),
  ('3219','Compania Panamena De Aviacion (COPA)','travel'),
  ('3220','Compania Faucett','travel'),
  ('3221','Transportes Aeros Militares','travel'),
  ('3222','Command Airways','travel'),
  ('3223','Comair','travel'),
  ('3226','Skyways','travel'),
  ('3228','Cayman Airways','travel'),
  ('3229','SAETA (Sociedad Ecuatorianos De Transportes Aereos)','travel'),
  ('3231','SAHSA (Servicio Aero De Honduras)','travel'),
  ('3233','Capitol Air HAVASU AIR (V) HAVASUAI (M) GUYANA AIR (V) GUYANA A (M) GOLDPAC AIR FREEDOM AIR (V) FREEDOM (M) CHINAEASTAIR (V) CHINAEAST (M) NORWEGIANAIR (V) NORWEGIAN (M) DOMINICA AIR (V) DOMINICA (M) MALMO AIR (V) MALMO AV (M) CSA AIRLINE (V) CSA (M) CROWN AIR COPA AIR (V) COPA (M) COMP FAU AIR (V) COMPANIA (M) TAME AIRLINE (V) TAME AIR (M) COMMAND AIR (V) COMMAND (M) COMAIR SKYWAYS AIR (V) SKYWAYS (M) CAYMANAIR SAETA AIR (V) SAETAAIR (M) SAHSA AIR (V) SAHSA (M) CAPITOL AIR 22','travel'),
  ('3234','Caribbean Airlines','travel'),
  ('3235','Brockway Air','travel'),
  ('3236','Air Arabia Airline','travel'),
  ('3238','Bemidji Aviation','travel'),
  ('3239','Bar Harbor Airlines','dining'),
  ('3240','Bahamasair','travel'),
  ('3241','Aviateca','travel'),
  ('3242','Avensa','travel'),
  ('3243','Austrian Air Service','travel'),
  ('3245','Easyjet','travel'),
  ('3246','Ryanair','travel'),
  ('3247','Gol Airlines','travel'),
  ('3248','Tam Airlines','travel'),
  ('3251','Aloha Airlines','travel'),
  ('3252','Antilean Airlines (ALM)','travel'),
  ('3253','America West AMERWEST','travel'),
  ('3254','U.S. Air Shuttle USAIRSHUTL','travel'),
  ('3256','Alaska Airlines','travel'),
  ('3259','American Trans Air','travel'),
  ('3260','Spirit Airlines','travel'),
  ('3261','Air China','travel'),
  ('3262','Reno Air RENO AIR','travel'),
  ('3263','Aero Servicio Carabobo CARIBBEANAIR (V) CARIBBEAN (M) BROCKWAY AIR AIR ARABIA (V) AIR ARAB (M) BEMIDJI AIR BARHARBORAIR (V) BARHARBO (M) BAHAMASAIR (V) BAHAMASA (M) AVIATECA AIR (V) AVIATECA (M) AVENSA AIR (V) AVENSA (M) AUST AIRSERV (V) AUSTRAIR (M) EASYJET AIR (V) EASYJET (M) RYANAIR GOL AIR (V) GOL (M) TAM AIR (V) TAM (M) ALOHA AIR ALM AIRLINE (V) ALM (M) ALASKA AIR (V) ALASKA A (M) ATA AIR SPIRIT AIR (V) SPIRIT (M) ASC AIRLINE (V) ASERCA (M) 23','travel'),
  ('3266','Air Seychelles','travel'),
  ('3267','Air Panama International','travel'),
  ('3273','Rica Hotels','travel'),
  ('3274','Inter Nor Hotels','travel'),
  ('3280','Air Jamaica','travel'),
  ('3281','Air Djibouti','travel'),
  ('3282','Air Djibouti','travel'),
  ('3284','Aero Virgin Islands AERVIRGINIS','travel'),
  ('3285','Aero Peru AEROPERU','travel'),
  ('3286','Aero Nicaraguensis','travel'),
  ('3287','Aero Coach Aviation','travel'),
  ('3292','Cyprus Airways','travel'),
  ('3293','Ecuatoriana','travel'),
  ('3294','Ethiopian Airlines','travel'),
  ('3295','Kenya Airways','travel'),
  ('3296','Air Berlin','travel'),
  ('3297','Tarom Romanian Air Transport','travel'),
  ('3298','Air Mauritius','travel'),
  ('3299','Wideroes Flyveselskap AIR SEYCH (V) AIR SEYC (M) AIR PANAMA (V) AIR PANA (M) AIR JAMAICA (V) AIR JAMA (M) AIR DJIBOUTI (V) AIR DJIB (M) AERONICARAG (V) AERO NIC (M) AEROCOACH AV (V) AEROCOAC (M) CYPRUS AIR (V) CYPRUSA (M) ECUATORIANA (V) ECUATORI (M) ETHIOPIAN AIR (V) ETHIOPIA (M) KENYA AIR (V) KENYAAIR (M) AIR BERLIN (V) AIRBERLIN (M) TAROM AIR AIRMAURITIUS (V) AIRMAURI (M) WIDEROES','travel'),
  ('3351','Affiliated Auto Rental','travel'),
  ('3352','American International','travel'),
  ('3353','Brooks Rent-A-Car','travel'),
  ('3354','Action Auto Rental','travel'),
  ('3355','Sixt Car Rental','travel'),
  ('3357','Hertz Rent-a-car','travel'),
  ('3359','Payless Car Rental','travel'),
  ('3360','Snappy Car Rental','travel'),
  ('3361','Airways','travel'),
  ('3362','Altra Auto Rental','travel'),
  ('3364','Agency Rent-A-Car','travel'),
  ('3366','Budget Rent-a-car','travel'),
  ('3368','Holiday Rent-A-Car','travel'),
  ('3370','Rent-A-Wreck','travel'),
  ('3374','Accent Rent-A-Car','travel'),
  ('3376','Ajax Rent-A-Car','travel'),
  ('3380','Triangle Rent-A-Car','travel'),
  ('3381','Europ Car','travel'),
  ('3385','Tropical Rent-A-Car','travel'),
  ('3386','Showcase Rental Cars','travel'),
  ('3387','Alamo Rent-A-Car','travel'),
  ('3388','Merchants Rent-A-Car','travel'),
  ('3389','Avis Rent-a-car','travel'),
  ('3390','Dollar Rent-A-Car','travel'),
  ('3391','Europe By Car','travel'),
  ('3393','National Car Rental','travel'),
  ('3394','Kemwell Group','travel'),
  ('3395','Thrifty Rent-a-car','travel'),
  ('3396','Tilden Rent-A-Car','travel'),
  ('3398','Econo-Car Rent-A-Car','travel'),
  ('3400','Auto Host Rental Cars','travel'),
  ('3405','Enterprise Rent-a-car','travel'),
  ('3409','General Rent-A-Car','travel'),
  ('3412','A1 Rent-A-Car 25','travel'),
  ('3414','Godfrey National','travel'),
  ('3420','Ansa International','travel'),
  ('3421','Allstate','travel'),
  ('3423','AVCAR','travel'),
  ('3425','Automate','travel'),
  ('3427','Avon Rent-A-Car','travel'),
  ('3428','Carey','travel'),
  ('3429','Insurance Rent-A-Car','insurance'),
  ('3430','Major Rent-A-Car','travel'),
  ('3431','Replacement Rent-A-Car','travel'),
  ('3432','Reserve Rent-A-Car','travel'),
  ('3433','Ugly Duckling Rent-A-Car','travel'),
  ('3435','Value Rent-A-Car','travel'),
  ('3436','Autohansa','travel'),
  ('3437','Cite','travel'),
  ('3438','Interent','travel'),
  ('3439','Milleville','travel'),
  ('3441','Advantage Rent A Car','travel'),
  ('3500','Lodging, individual hotel chain','travel'),
  ('3501','Holiday Inns, Holiday Inn Express','travel'),
  ('3502','Best Western Hotels','travel'),
  ('3503','Sheraton Hotels','travel'),
  ('3504','Hilton Hotels','travel'),
  ('3505','Trusthouse Forte','travel'),
  ('3506','Golden Tulip','travel'),
  ('3507','Friendship Inns International','travel'),
  ('3508','Quality International','travel'),
  ('3509','Marriott Hotels','travel'),
  ('3510','Days Inns Of America','travel'),
  ('3511','Arabella Hotels','travel'),
  ('3512','Inter-continental Hotels','travel'),
  ('3513','Westin Hotels','travel'),
  ('3514','Amerisuites','travel'),
  ('3515','Rodeway Inns International','travel'),
  ('3516','La Quinta Motor Inns','travel'),
  ('3517','Americana Hotels Corporation','travel'),
  ('3518','Sol Hotels','travel'),
  ('3519','PLM/ETAP International','travel'),
  ('3520','Meridien','travel'),
  ('3521','Crest Hotels','travel'),
  ('3522','Tokyo Group','travel'),
  ('3523','Peninsula Hotels','travel'),
  ('3524','Welcomgroup','travel'),
  ('3525','Dunfey Hotels','travel'),
  ('3526','Prince Hotels','travel'),
  ('3527','Downtowner Passport','travel'),
  ('3528','Thunderbird/Red Lion','travel'),
  ('3529','CP (Canadian Pacific)','travel'),
  ('3530','Renaissance Hotels, Stouffer Hotels','travel'),
  ('3531','Kauai Coconut Beach Resort','travel'),
  ('3532','Royal Kona Resort','travel'),
  ('3533','Hotel Ibis','travel'),
  ('3534','Southern Pacific Hotel','travel'),
  ('3535','Hilton International','travel'),
  ('3536','AMFAC Hotels','travel'),
  ('3537','Ana Hotels','travel'),
  ('3538','Concorde Hotels','travel'),
  ('3539','Summerfield Suites Hotel','travel'),
  ('3540','Iberotel','travel'),
  ('3541','Hotel Okura','travel'),
  ('3542','Royal Hotels','travel'),
  ('3543','Four Seasons Hotels','travel'),
  ('3544','Cigahotels','travel'),
  ('3545','Shangri-la International','travel'),
  ('3546','Hotel Sierra','travel'),
  ('3547','Breakers Resort','travel'),
  ('3548','Hotels Melia','travel'),
  ('3549','Auberge Des Governeurs','travel'),
  ('3550','Regal 8 Inns 27','travel'),
  ('3551','Mirage Hotel and Casino','travel'),
  ('3552','Coast Hotels','travel'),
  ('3553','Parks Inns International','travel'),
  ('3554','Pinehurst Resort','travel'),
  ('3555','Treasure Island Hotel and Casino','travel'),
  ('3556','Barton Creek Resort','travel'),
  ('3557','Manhattan East Suite Hotels','travel'),
  ('3558','Jolly Hotels','travel'),
  ('3559','Candlewood Suites','travel'),
  ('3560','Aladdin Resort and Casino','travel'),
  ('3561','Golden Nugget','travel'),
  ('3562','Comfort Hotel International','travel'),
  ('3563','Journeys End Motels','travel'),
  ('3564','Sams Town Hotel and Casino','travel'),
  ('3565','Relax Inns','travel'),
  ('3566','Garden Place Hotel','travel'),
  ('3567','Soho Grand Hotel','travel'),
  ('3568','Ladbroke Hotels','travel'),
  ('3569','Tribeca Grand Hotel','travel'),
  ('3570','Grand Met Forum Hotels','travel'),
  ('3571','Grand Wailea Resort','travel'),
  ('3572','Miyako Hotel/Kintetsu','travel'),
  ('3573','Sandman Hotels','travel'),
  ('3574','Venture Inn','travel'),
  ('3575','Vagabond Hotels','travel'),
  ('3576','La Quinta Resort','travel'),
  ('3577','Mandarin International','travel'),
  ('3578','Frankenmuth Bavarian','travel'),
  ('3579','Hotel Mercure','travel'),
  ('3580','Hotel Del Coronado','travel'),
  ('3581','Delta Hotel','travel'),
  ('3582','California Hotel and Casino','travel'),
  ('3583','Sas Hotels','travel'),
  ('3584','Princess Hotels International','travel'),
  ('3585','Hungar Hotels','travel'),
  ('3586','Sokos Hotel','travel'),
  ('3587','Doral Hotels','travel'),
  ('3588','Helmsley Hotels 28','travel'),
  ('3589','Doral Golf Resort','travel'),
  ('3590','Fairmont Hotels Corporation','travel'),
  ('3591','Sonesta International Hotels','travel'),
  ('3592','Omni International','travel'),
  ('3593','Cunard Hotels','travel'),
  ('3594','Arizona Biltmore','travel'),
  ('3595','Hospitality Inns','health'),
  ('3596','Wynn Las Vegas','travel'),
  ('3597','Riverside Resort and Casino','travel'),
  ('3598','Hilton Conrad','travel'),
  ('3599','Pannonia Hotels','travel'),
  ('3600','Saddlebrook Resort–Tampa','travel'),
  ('3601','Tradewinds Resort','travel'),
  ('3602','Hudson Hotel','travel'),
  ('3603','Noahs Hotel (Melbourne)','travel'),
  ('3604','Hilton Garden Inn','travel'),
  ('3605','Jurys Doyle Hotel Group','travel'),
  ('3606','Jefferson Hotel','travel'),
  ('3607','Fontainebleau Resort','travel'),
  ('3608','Gaylord Opryland','travel'),
  ('3609','Gaylord Palms','travel'),
  ('3610','Gaylord Texan','travel'),
  ('3611','C MON INN','travel'),
  ('3612','Moevenpick','travel'),
  ('3613','Microtel Inn and Suites','travel'),
  ('3614','AmericInn','travel'),
  ('3615','Travelodge Motels','travel'),
  ('3616','Hermitage Hotels','travel'),
  ('3617','America’s Best Value Inn','travel'),
  ('3618','Great Wolf','travel'),
  ('3619','Aloft','travel'),
  ('3620','Binions Horseshoe Club','shopping'),
  ('3621','Extended Stay','travel'),
  ('3622','Merlin Hotel (Perth)','travel'),
  ('3623','Dorint Hotels','travel'),
  ('3624','Lady Luck Hotel and Casino','travel'),
  ('3625','Hotel Universal','travel'),
  ('3626','Studio Plus 29','travel'),
  ('3627','Extended Stay America','travel'),
  ('3628','Excalibur Hotel and Casino','travel'),
  ('3629','Dan Hotels','travel'),
  ('3630','Extended Stay Deluxe','travel'),
  ('3631','Sleep Inn','travel'),
  ('3632','The Phoenician','travel'),
  ('3633','Rank Hotels','travel'),
  ('3634','Swissotel','travel'),
  ('3635','Reso Hotels','travel'),
  ('3636','Sarova Hotels','travel'),
  ('3637','Ramada Inns','travel'),
  ('3638','Howard Johnson','travel'),
  ('3639','Mount Charlotte Hotels','travel'),
  ('3640','Hyatt Hotel','travel'),
  ('3641','Sofitel Hotels','travel'),
  ('3642','Novotel Sieh (Accor)','travel'),
  ('3643','Steigenberger','travel'),
  ('3644','Econo-Travel Motor Hotel','travel'),
  ('3645','Queens Moat Houses','travel'),
  ('3646','Swallow Hotels','travel'),
  ('3647','Grupo Hotels HUSA SA','travel'),
  ('3648','De Vere Hotels','travel'),
  ('3649','Radisson Hotels','travel'),
  ('3650','Red Roof Inns','travel'),
  ('3651','Imperial London Hotels','travel'),
  ('3652','Embassy Hotels','travel'),
  ('3653','Penta Hotels','travel'),
  ('3654','Loews Hotels','travel'),
  ('3655','Scandic Hotels','travel'),
  ('3656','Sara Hotels','travel'),
  ('3657','Oberoi Hotels','travel'),
  ('3658','New Otani Hotels','travel'),
  ('3659','Taj Hotels Intl','travel'),
  ('3660','Knights Inn','travel'),
  ('3661','Metropole Hotels','travel'),
  ('3662','Circus Circus Hotel and Casino','travel'),
  ('3663','Hoteles El Presidente','travel'),
  ('3664','Flag Inns 30','travel'),
  ('3665','Hampton Inns','travel'),
  ('3666','Stakis Hotels','travel'),
  ('3667','Luxor Hotel and Casino','travel'),
  ('3668','Maritim','travel'),
  ('3669','Eldorado Hotel and Casino','travel'),
  ('3670','Arcade','entertainment'),
  ('3671','Arctia','travel'),
  ('3672','Campanile','travel'),
  ('3673','Ibusz Hotels','travel'),
  ('3674','Rantasipi Hotels','travel'),
  ('3675','Interhotel Cedok','travel'),
  ('3676','Monte Carlo Hotel and Casino','travel'),
  ('3677','Climat De France','travel'),
  ('3678','Cumulus Hotels','travel'),
  ('3679','Silver Legacy Hotel and Casino','travel'),
  ('3680','Hoteis Othan','travel'),
  ('3681','Adams Mark','travel'),
  ('3682','Sahara Hotel and Casino','travel'),
  ('3683','Bradbury Suites','travel'),
  ('3684','Budget Host Inns','travel'),
  ('3685','Budgetel','travel'),
  ('3686','Suisse Chalet','travel'),
  ('3687','Clarion Hotel','travel'),
  ('3688','Compri Hotel','travel'),
  ('3689','Consort','travel'),
  ('3690','Courtyard By Marriott','travel'),
  ('3691','Dillon Inn','travel'),
  ('3692','Doubletree Hotels','travel'),
  ('3693','Drury Inn','travel'),
  ('3694','Economy Inns Of America','travel'),
  ('3695','Embassy Suites','travel'),
  ('3696','Excel Inn','travel'),
  ('3697','Fairfield Hotel','travel'),
  ('3698','Harley Hotel','travel'),
  ('3699','Midway Motor Lodge','travel'),
  ('3700','Motel 6','travel'),
  ('3701','La Mansion Del Rio','travel'),
  ('3702','Registry Hotels 31','travel'),
  ('3703','Residence Inn','travel'),
  ('3704','Royce Hotel','travel'),
  ('3705','Sandman Inn','travel'),
  ('3706','Shilo Inn','travel'),
  ('3707','Shoneys Inn','travel'),
  ('3708','Virgin River Hotel and Casino','travel'),
  ('3709','Super 8 Motel','travel'),
  ('3710','The Ritz Carlton Hotels','travel'),
  ('3711','Flag Inns (Australia)','travel'),
  ('3712','Buffalo Bills Hotel and Casino','travel'),
  ('3713','Quality Pacific Hotel','travel'),
  ('3714','Four Seasons (Australia)','travel'),
  ('3715','Fairfield Inn','travel'),
  ('3716','Carlton Hotels','travel'),
  ('3717','City Lodge Hotels','travel'),
  ('3718','Karos Hotels','travel'),
  ('3719','Protea Hotels','travel'),
  ('3720','Southern Sun Hotels','travel'),
  ('3721','Hilton Conrad','travel'),
  ('3722','Wyndham','travel'),
  ('3723','Rica Hotels','travel'),
  ('3724','Inter Nor Hotels','travel'),
  ('3725','Sea Pines Resort','travel'),
  ('3726','Rio Suites','travel'),
  ('3727','Broadmoor Hotel','travel'),
  ('3728','Ballys Hotel and Casino','travel'),
  ('3729','John Ascuagas Nugget','travel'),
  ('3730','MGM Grand Hotel','travel'),
  ('3731','Harrah’s Hotels and Casinos','travel'),
  ('3732','Opryland Hotel','travel'),
  ('3733','Boca Raton Resort','travel'),
  ('3734','Harvey Bristol Hotels','travel'),
  ('3735','Masters Economy Inns','travel'),
  ('3736','Colorado Belle Edgewater Resort','travel'),
  ('3737','Riviera Hotel and Casino','travel'),
  ('3738','Tropicana Resort and Casino','travel'),
  ('3739','Woodside Hotels and Resorts','travel'),
  ('3740','Towneplace Suites 32','travel'),
  ('3741','Millennium Broadway Hotel','travel'),
  ('3742','Club Med','travel'),
  ('3743','Biltmore Hotel and Suites','travel'),
  ('3744','Carefree Resorts','travel'),
  ('3745','St. Regis Hotel','travel'),
  ('3746','The Eliot Hotel','travel'),
  ('3747','Club Corporation/Club Resorts','travel'),
  ('3748','Wellesley Inns','travel'),
  ('3749','Beverly Hills Hotel','travel'),
  ('3750','Crowne Plaza Hotels','travel'),
  ('3751','Homewood Suites','travel'),
  ('3752','Peabody Hotels','travel'),
  ('3753','Greenbriar Resorts','travel'),
  ('3754','Amelia Island Plantation','travel'),
  ('3755','Homestead','travel'),
  ('3757','Canyon Ranch','travel'),
  ('3758','Kahala Mandarin Oriental Hotel','travel'),
  ('3759','Orchid At Mauna Lai','travel'),
  ('3760','Halekulani Hotel/Waikiki Parc','travel'),
  ('3761','Primadonna Hotel and Casino','travel'),
  ('3762','Whiskey Pete’s Hotel and Casino','travel'),
  ('3763','Chateau Elan Winery and Resort','travel'),
  ('3764','Beau Rivage Hotel and Casino','travel'),
  ('3765','Bellagio','travel'),
  ('3766','Fremont Hotel and Casino','travel'),
  ('3767','Main Street Station Hotel and Casino','travel'),
  ('3768','Silver Star Hotel and Casino','travel'),
  ('3769','Stratosphere Hotel and Casino','travel'),
  ('3770','Springhill Suites','travel'),
  ('3771','Caesars Hotel and Casino','travel'),
  ('3772','Nemacolin Woodlands','travel'),
  ('3773','Venetian Resort Hotel and Casino','travel'),
  ('3774','New York-New York Hotel and Casino','travel'),
  ('3775','Sands Resort','travel'),
  ('3776','Nevele Grande Resort and Country Club','travel'),
  ('3777','Mandalay Bay Resort','travel'),
  ('3778','Four Points Hotels','travel'),
  ('3779','W Hotels','travel'),
  ('3780','Disney Resorts','travel'),
  ('3781','Patricia Grand Resort Hotels','travel'),
  ('3782','Rosen Hotel and Resorts','travel'),
  ('3783','Town and Country Resort and Convention Center','travel'),
  ('3784','First Hospitality Hotels','health'),
  ('3785','Outrigger Hotels and Resorts','travel'),
  ('3786','Ohana Hotels of Hawaii','travel'),
  ('3787','Caribe Royal Resort Suite and Villas','travel'),
  ('3788','Ala Moana Hotel','travel'),
  ('3789','Smugglers Notch Resort','travel'),
  ('3790','Raffles Hotels','travel'),
  ('3791','Staybridge Suites','travel'),
  ('3792','Claridge Casino Hotel','travel'),
  ('3793','The Flamingo Hotels','travel'),
  ('3794','Grand Casino Hotels','travel'),
  ('3795','Paris Las Vegas Hotel','travel'),
  ('3796','Peppermill Hotel Casino','travel'),
  ('3797','Atlantic City Hilton','travel'),
  ('3798','Embassy Vacation Resort','travel'),
  ('3799','Hale Koa Hotel','travel'),
  ('3800','Homestead Suites','travel'),
  ('3801','Wilderness Hotel and Resort','travel'),
  ('3802','The Palace Hotel','travel'),
  ('3803','The Wigwam Golf Resort and Spa','health'),
  ('3804','The Diplomat Country Club and Spa','health'),
  ('3805','The Atlantic','travel'),
  ('3806','Princeville Resort','travel'),
  ('3807','Element','travel'),
  ('3808','LXR (Luxury Resorts)','travel'),
  ('3809','Settle Inn','travel'),
  ('3810','La Costa Resort','travel'),
  ('3811','Premier Travel Inns','travel'),
  ('3812','Hyatt Place','travel'),
  ('3813','Hotel Indigo','travel'),
  ('3814','The Roosevelt Hotel NY','travel'),
  ('3815','Nickelodeon Family Suites by Holiday Inn','travel'),
  ('3816','Home2Suites','travel'),
  ('3817','Affinia 34','travel'),
  ('3818','Mainstay Suites','travel'),
  ('3819','Oxford Suites','travel'),
  ('3820','Jumeirah Essex House','travel'),
  ('3821','Caribe Royal','travel'),
  ('3822','Crossland','travel'),
  ('3823','Grand Sierra Resort','travel'),
  ('3824','Aria','travel'),
  ('3825','Vdara','travel'),
  ('3826','Autograph','travel'),
  ('3827','Galt House','travel'),
  ('3828','Cosmopolitan of Las Vegas','travel'),
  ('3829','Country Inn By Carlson','travel'),
  ('3830','Park Plaza Hotel','travel'),
  ('3831','Waldorf','travel'),
  ('3837','Hoshino Resorts','travel'),
  ('4011','Railroads–Freight','transport'),
  ('4111','Local/suburban Commuter Passenger Transportation – Railroads, Ferries, Local Water Transportation','transport'),
  ('4112','Passenger Railways','transport'),
  ('4119','Ambulance Services','health'),
  ('4121','Taxicabs and Limousines','transport'),
  ('4131','Bus Lines, Including Charters, Tour Buses','transport'),
  ('4214','Motor Freight Carriers, Moving and Storage Companies, Trucking – Local/long Distance, Delivery Services – Local','other'),
  ('4215','Courier Services – Air Or Ground, Freight Forwarders','shopping'),
  ('4225','Public Warehousing, Storage','other'),
  ('4411','Cruise and Steamship Lines','travel'),
  ('4457','Boat Leases and Boat Rentals','travel'),
  ('4468','Marinas, Marine Service/Supplies','travel'),
  ('4511','Airlines, Air Carriers','travel'),
  ('4582','Airports, Airport Terminals, Flying Fields','travel'),
  ('4722','Travel Agencies and Tour Operations','travel'),
  ('4723','Package Tour Operators (Germany Only)','travel'),
  ('4761','Telemarketing of Travel Related Services and Vitamins','online'),
  ('4784','Toll and Bridge Fees','transport'),
  ('4789','Transportation Services - Not Elsewhere Classified','transport'),
  ('4812','Telecommunications Equipment Including Telephone Sales','utilities'),
  ('4813','Key-Entry Telecom Merchant providing single local and long-distance phone calls using a central access number in a non-face-to-face environment using key entry Telecommunication Services including but not limited to prepaid phone services and recurring phone services','utilities'),
  ('4814','Fax Services, Telecommunication Services','utilities'),
  ('4816','Computer Network Services','utilities'),
  ('4821','Telegraph Services Wire Transfer Money Orders (V, D, G, X)','utilities'),
  ('4829','Wire Transfers and Money Orders','financial'),
  ('4899','Cable, Satellite and Other Pay Television/radio/streaming Services','utilities'),
  ('4900','Electric, Gas, Sanitary and Water Utilities','utilities'),
  ('5013','Motor Vehicle Supplies and New Parts','other'),
  ('5021','Office and Commercial Furniture','shopping'),
  ('5039','Construction Materials, Not Elsewhere Classified','other'),
  ('5044','Office','other'),
  ('5045','Computers, Computer Peripheral Equipment, Not Elsewhere Classified','other'),
  ('5046','Commercial Equipment Not Elsewhere Classified','other'),
  ('5047','Medical, Dental Ophthalmic, Hospital Equipment and Supplies','health'),
  ('5051','Metal Service Centers and Offices','other'),
  ('5065','Electrical Parts and Equipment','other'),
  ('5072','Hardware Equipment and Supplies','shopping'),
  ('5074','Plumbing and Heating Equipment','home'),
  ('5085','Industrial Supplies Not Elsewhere Classified','other'),
  ('5094','Precious Stones and Metals, Watches and Jewelry','shopping'),
  ('5099','Durable Goods Not Elsewhere Classified','other'),
  ('5111','Stationery, Office Supplies, Printing, and Writing Paper','shopping'),
  ('5122','Drugs, Drug Proprietors and Druggists Sundries','health'),
  ('5131','Piece Goods, Notions, and Other Dry Goods','other'),
  ('5137','Men’s Women’s and Children’s Uniforms and Commercial Clothing','shopping'),
  ('5139','Commercial Footware','other'),
  ('5169','Chemicals and Allied Products, Not Elsewhere Classified','other'),
  ('5172','Petroleum and Petroleum Products','fuel'),
  ('5192','Books, Periodicals, and Newspapers','shopping'),
  ('5193','Florists’ Supplies, Nursery Stock and Flowers','shopping'),
  ('5198','Paints, Varnishes and Supplies','shopping'),
  ('5199','Non-Durable Goods Not Elsewhere Classified','other'),
  ('5200','Home Supply Warehouse Stores','shopping'),
  ('5211','Building Materials, Lumber Stores','shopping'),
  ('5231','Glass, Paint, and Wallpaper Stores','shopping'),
  ('5251','Hardware Stores','shopping'),
  ('5261','Nurseries – Lawn and Garden Supply Store','shopping'),
  ('5262','Marketplaces','online'),
  ('5271','Mobile Home Dealers','shopping'),
  ('5299','Warehouse Club Gas','fuel'),
  ('5300','Wholesale Clubs','shopping'),
  ('5309','Duty Free Store','shopping'),
  ('5310','Discount Stores','shopping'),
  ('5311','Department Stores','shopping'),
  ('5331','Variety Stores','shopping'),
  ('5399','Miscellaneous General Merchandise','shopping'),
  ('5411','Grocery Stores, Supermarkets','groceries'),
  ('5422','Meat Provisioners – Freezer and Locker','groceries'),
  ('5441','Candy, Nut, and Confectionery Stores','groceries'),
  ('5451','Dairy Products Stores','groceries'),
  ('5462','Bakeries','dining'),
  ('5499','Miscellaneous Food Stores – Convenience Stores and Specialty Markets','groceries'),
  ('5511','Car and Truck Dealers new and Used Sales, Service, Repairs, Parts, and Leasing','transport'),
  ('5521','Automobile and Truck Dealers–(Used Only)–Sales','shopping'),
  ('5531','Auto and Home Supply Outlets','transport'),
  ('5532','Automotive Tire Stores','transport'),
  ('5533','Automotive Parts, Accessories Stores','transport'),
  ('5541','Service Stations with Or Without Ancillary Services','fuel'),
  ('5542','Fuel Dispenser, Automated','fuel'),
  ('5551','Boat Dealers','shopping'),
  ('5552','Electric Vehicle (EV) Charging services','fuel'),
  ('5561','Camper Dealers, Recreational and Utility Trailers','shopping'),
  ('5571','Motorcycle Shops and Dealers','transport'),
  ('5592','Motor Home Dealers','shopping'),
  ('5598','Snowmobile Dealers','shopping'),
  ('5599','Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers–Not Elsewhere Classified','shopping'),
  ('5611','Men’s and Boy’s Clothing and Accessories Stores','shopping'),
  ('5621','Women’s Ready-to-wear Stores','shopping'),
  ('5631','Women’s Accessory and Specialty Shops','shopping'),
  ('5641','Children’s and Infant’s Wear Stores','shopping'),
  ('5651','Family Clothing Stores','shopping'),
  ('5655','Sports Apparel, Riding Apparel Stores','shopping'),
  ('5661','Shoe Stores','shopping'),
  ('5681','Furriers and Fur Shops','shopping'),
  ('5691','Men’s and Women’s Clothing Stores','shopping'),
  ('5697','Tailors, Seamstress, Mending, and Alterations','shopping'),
  ('5698','Wig and Toupee Shops','shopping'),
  ('5699','Miscellaneous Apparel and Accessory Shops','shopping'),
  ('5712','Furniture, Home Furnishings, and Equipment Stores, Except Appliances','shopping'),
  ('5713','Floor Covering Stores','shopping'),
  ('5714','Drapery, Window Covering and Upholstery Stores','shopping'),
  ('5715','Alcoholic Beverage Wholesalers','shopping'),
  ('5718','Fireplace, Fireplace Screens, and Accessories Stores','shopping'),
  ('5719','Miscellaneous Home Furnishing Specialty Stores','shopping'),
  ('5722','Household Appliance Stores','shopping'),
  ('5732','Electronics Sale','shopping'),
  ('5733','Music Stores, Musical Instruments, Piano Sheet Music','shopping'),
  ('5734','Computer Software Stores','shopping'),
  ('5735','Record Shops','shopping'),
  ('5811','Caterers','dining'),
  ('5812','Eating Places and Restaurants','dining'),
  ('5813','Bars','dining'),
  ('5814','Fast Food Restaurants','dining'),
  ('5815','Digital Goods — Media, books, movies, music','online'),
  ('5816','Digital Goods — Games','online'),
  ('5817','Digital Goods — Software Applications excluding games','online'),
  ('5818','Digital Goods — Multi-category','online'),
  ('5912','Drug Stores and Pharmacies','health'),
  ('5921','Package Stores – Beer, Wine, and Liquor','groceries'),
  ('5931','Second Hand Stores','shopping'),
  ('5932','Antique Shops','shopping'),
  ('5933','Pawn Shops','other'),
  ('5935','Wrecking and Salvage Yards','other'),
  ('5937','Antique Reproduction Stores','shopping'),
  ('5940','Bicycle Shops – Sales and Service','shopping'),
  ('5941','Sporting Goods Stores','shopping'),
  ('5942','Book Stores','shopping'),
  ('5943','Stationery Stores, Office and School Supply Stores','shopping'),
  ('5944','Watch, Clock, Jewelry, and Silverware Stores','shopping'),
  ('5945','Hobby, Toy, and Game Shops','shopping'),
  ('5946','Camera and Photographic Supply Stores','shopping'),
  ('5947','Card Shops, Gift, Novelty, and Souvenir Shops','shopping'),
  ('5948','Luggage and Leather Goods Shops','shopping'),
  ('5949','Fabric, Needlework, Piece Goods and Sewing Stores','shopping'),
  ('5950','Crystal and Glassware Stores','shopping'),
  ('5960','Direct Marketing Insurance Services','insurance'),
  ('5961','Mail Order Houses Including Catalog Order Stores','shopping'),
  ('5962','Direct Marketing–Travel Related Arrangement Services','online'),
  ('5963','Door-to-Door Sales','online'),
  ('5964','Direct Marketing – Catalog Merchant','online'),
  ('5965','Direct Marketing – Combination Catalog and Retail Merchant','online'),
  ('5966','Direct Marketing–Outbound Telemarketing Merchants','online'),
  ('5967','Direct Marketing – Inbound Telemarketing Merchant','online'),
  ('5968','Direct Marketing – Continuity/subscription Merchant','online'),
  ('5969','Direct Marketing – Not Elsewhere Classified','online'),
  ('5970','Artist’s Supply and Craft Shops','shopping'),
  ('5971','Art Dealers and Galleries','shopping'),
  ('5972','Electronics Sales','shopping'),
  ('5973','Religious Goods Stores','charity'),
  ('5974','Rubber Stamp Store','shopping'),
  ('5975','Hearing Aids – Sales, Service, and Supply Stores','shopping'),
  ('5976','Orthopedic Goods–Artificial Limb Stores','shopping'),
  ('5977','Cosmetic Stores','shopping'),
  ('5978','Typewriter Stores–Rentals, Sales, Service','shopping'),
  ('5983','Fuel Dealers–Coal, Fuel Oil, Liquefied Petroleum, Wood','fuel'),
  ('5992','Florists','shopping'),
  ('5993','Cigar Stores and Stands','shopping'),
  ('5994','News Dealers and Newsstands','shopping'),
  ('5995','Pet Shops, Pet Foods, and Supplies Stores','shopping'),
  ('5996','Swimming Pools – Sales, Service, and Supplies','home'),
  ('5997','Electric Razor Stores–Sales and Service','shopping'),
  ('5998','Tent and Awning Shops','shopping'),
  ('5999','Miscellaneous and Specialty Retail Stores','shopping'),
  ('6010','Financial Institutions – Manual Cash Disbursements','financial'),
  ('6011','Member Financial Institution–Automated Cash Disbursements 9','financial'),
  ('6012','Financial Institutions – Merchandise and Services','financial'),
  ('6050','Quasi Cash–Member Financial Institution','financial'),
  ('6051','Non-financial Institutions – Foreign Currency, Money Orders not Wire Transfer and Travelers Cheques','financial'),
  ('6211','Security Brokers/dealers','financial'),
  ('6236','Aero Servicio Carabobo','travel'),
  ('6300','Insurance Sales, Underwriting, and Premiums','insurance'),
  ('6381','Insurance–Premiums','insurance'),
  ('6399','Insurance, other','insurance'),
  ('6513','Real Estate Agents and Managers','rental'),
  ('6529','Remote Stored Value Load — Member Financial Institution','financial'),
  ('6530','Remove Stored Value Load — Merchant','financial'),
  ('6532','Payment transaction, member financial institution','financial'),
  ('6533','Payment Transaction — Merchant','financial'),
  ('6534','Money transfer, member financial institution','financial'),
  ('6535','Value Purchase–Member Financial Institution','financial'),
  ('6536','MoneySend Intracountry','financial'),
  ('6537','MoneySend Intercountry','financial'),
  ('6538','MoneySend Funding','financial'),
  ('6539','Funding Transaction (Excluding MoneySend)','financial'),
  ('6540','Non-financial Institutions – Stored Value Card Purchase/load; Poi Funding Transactions','financial'),
  ('6611','Overpayments','financial'),
  ('6760','Savings Bonds','financial'),
  ('7011','Lodging – Hotels, Motels, Resorts, Central Reservation Services','travel'),
  ('7012','Timeshares','travel'),
  ('7032','Sporting and Recreational Camps','entertainment'),
  ('7033','Campgrounds and Trailer Parks','travel'),
  ('7210','Laundry, Cleaning, and Garment Services','other'),
  ('7211','Laundry Services–Family and Commercial','other'),
  ('7216','Dry Cleaners','other'),
  ('7217','Carpet and Upholstery Cleaning','home'),
  ('7221','Photographic Studios','other'),
  ('7230','Barber and Beauty Shops','health'),
  ('7251','Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops','home'),
  ('7261','Funeral Service and Crematories','other'),
  ('7273','Dating Services','other'),
  ('7276','Tax Preparation Service','other'),
  ('7277','Counselling Service – Debt, Marriage, Personal','other'),
  ('7278','Buying and Shopping Services and Clubs','other'),
  ('7280','Hospital Patient-Personal Funds Withdrawal 10','health'),
  ('7295','Babysitting Services','other'),
  ('7296','Clothing Rental–Costumes, Uniforms and Formal Wear','other'),
  ('7297','Massage Parlors','health'),
  ('7298','Health and Beauty Shops','health'),
  ('7299','Miscellaneous Personal Services not Elsewhere Classified','health'),
  ('7311','Advertising Services','other'),
  ('7321','Consumer Credit Reporting Agencies','financial'),
  ('7332','Blueprinting and Photocopying Services','other'),
  ('7333','Commercial Photography, Art and Graphics','other'),
  ('7338','Quick Copy, Reproduction and Blueprinting Services','other'),
  ('7339','Stenographic and Secretarial Support Services','other'),
  ('7342','Exterminating and Disinfecting Services','home'),
  ('7349','Cleaning and Maintenance, Janitorial Services','home'),
  ('7361','Employment Agencies, Temporary Help Services','other'),
  ('7372','Computer Programming, Integrated Systems Design and Data Processing Services','utilities'),
  ('7375','Information Retrieval Services','utilities'),
  ('7379','Computer Maintenance and Repair Services, Not Elsewhere Classified','utilities'),
  ('7392','Management, Consulting, and Public Relations Services','other'),
  ('7393','Detective Agencies, Protective Agencies, Security Services including Armored Cars, Guard Dogs','other'),
  ('7394','Equipment Rental and Leasing Services, Tool Rental, Furniture Rental, and Appliance Rental','other'),
  ('7395','Photo Developing, Photofinishing Laboratories','other'),
  ('7399','Business Services, Not Elsewhere Classified','other'),
  ('7512','Car Rental Companies','travel'),
  ('7513','Truck and Utility Trailer Rentals','utilities'),
  ('7519','Motor Home and Recreational Vehicle Rental','entertainment'),
  ('7523','Automobile Parking Lots and Garages','transport'),
  ('7524','Express Payment Service Merchants–Parking Lots and Garages 11','transport'),
  ('7531','Automotive Body Repair Shops','transport'),
  ('7534','Tire Retreading and Repair Shops','transport'),
  ('7535','Automotive Paint Shops','transport'),
  ('7538','Automotive Service Shops','transport'),
  ('7542','Car Washes','transport'),
  ('7549','Towing Services','transport'),
  ('7622','Electronics Repair Shops','home'),
  ('7623','Air Conditioning and Refrigeration Repair Shops','home'),
  ('7629','Electrical and Small Appliance Repair Shops','home'),
  ('7631','Clock, Jewelry and Watch Repair Shops','home'),
  ('7641','Furniture Reupholstery, Furniture Repair, and Furniture Refinishing','home'),
  ('7692','Welding Repair','home'),
  ('7699','Miscellaneous Repair Shops and Related Services','home'),
  ('7800','Government Owned Lottery','government'),
  ('7801','Government-Licensed Casinos (Online or Internet','financial'),
  ('7802','Government-Licensed Horse/Dog Racing','financial'),
  ('7829','Motion Picture and Video Tape Production and Distribution','entertainment'),
  ('7832','Motion Picture Theaters','entertainment'),
  ('7833','Express Payment Service — Motion Picture Theater','entertainment'),
  ('7841','DVD/Video Tape Rental Stores','shopping'),
  ('7911','Dance Halls','entertainment'),
  ('7922','Theatrical Producers except Motion Pictures, Ticket Agencies','entertainment'),
  ('7929','Bands, Orchestras, and Miscellaneous Entertainers not Elsewhere Classified','entertainment'),
  ('7932','Billiard and Pool Establishments','entertainment'),
  ('7933','Bowling Alleys','entertainment'),
  ('7941','Commercial Sports, Athletic Fields, Professional Sports Clubs, and Sport Promoters','entertainment'),
  ('7991','Tourist Attractions and Exhibits','entertainment'),
  ('7992','Golf Courses – Public','entertainment'),
  ('7993','Video Amusement Game Supplies','entertainment'),
  ('7994','Video Game Arcades/establishments','entertainment'),
  ('7995','Betting, lottery and casino gaming','financial'),
  ('7996','Amusement Parks, Carnivals, Circuses, Fortune Tellers','entertainment'),
  ('7997','Membership Clubs sports, Recreation, Athletic, Country Clubs, and Private Golf Courses','entertainment'),
  ('7998','Aquariums, Sea-aquariums, Dolphinariums','entertainment'),
  ('7999','Recreation Services not Elsewhere Classified','entertainment'),
  ('8011','Doctors and Physicians not Elsewhere Classified','health'),
  ('8021','Dentists and Orthodontists','health'),
  ('8031','Osteopaths','health'),
  ('8041','Chiropractors','health'),
  ('8042','Optometrists and Ophthalmologists','health'),
  ('8043','Opticians, Opticians Goods and Eyeglasses','health'),
  ('8044','Optical Goods and Eyeglasses','health'),
  ('8049','Chiropodists, Podiatrists','health'),
  ('8050','Nursing and Personal Care Facilities','health'),
  ('8062','Hospitals','health'),
  ('8071','Medical and Dental Laboratories','health'),
  ('8099','Medical Services and Health Practitioners not Elsewhere Classified','health'),
  ('8111','Attorneys, Legal Services','government'),
  ('8211','Elementary and Secondary Schools','education'),
  ('8220','Colleges, Junior Colleges, Universities, and Professional Schools','education'),
  ('8241','Schools, Correspondence','education'),
  ('8244','Business and Secretarial Schools','education'),
  ('8249','Vocational Schools and Trade Schools','education'),
  ('8299','Schools and Educational Services not Elsewhere Classified','education'),
  ('8351','Child Care Services','education'),
  ('8398','Charitable and Social Service Organizations','charity'),
  ('8641','Civic, Fraternal, and Social Associations','charity'),
  ('8651','Organizations, Political','charity'),
  ('8661','Organizations, Religious','charity'),
  ('8675','Automobile Associations','charity'),
  ('8699','Membership Organizations, Not Elsewhere Classified','charity'),
  ('8734','Testing Laboratories (Non-Medical)','health'),
  ('8743','Testing Laboratories (Non-Medical)','health'),
  ('8911','Architectural, Engineering and Surveying Services','other'),
  ('8931','Accounting, Auditing, and Bookkeeping Services','shopping'),
  ('8999','Professional Services not Elsewhere Defined','government'),
  ('9034','I-Purchasing Pilot','other'),
  ('9211','Court Costs, Including Alimony and Child Support','government'),
  ('9222','Fines','government'),
  ('9223','Bail and Bond Payments','government'),
  ('9311','Tax Payments','government'),
  ('9399','Government Services not Elsewhere Classified','government'),
  ('9401','I-Purchasing Pilot','government'),
  ('9402','Postal Services – Government Only','government'),
  ('9405','Intra-Government Purchases–Government Only','government'),
  ('9700','Automated Referral Service','government'),
  ('9701','Visa Credential Server','government'),
  ('9702','GCAS Emergency Services','government'),
  ('9751','UK Supermarkets, Electronic Hot File','groceries'),
  ('9752','UK Petrol Stations, Electronic Hot File','fuel'),
  ('9754','Gambling-Horse, Dog Racing, State Lottery','financial'),
  ('9950','Intra-Company Purchases V,M','government');

-- MCCs that most Singapore cards exclude from bonus earning. Seeded as a
-- starting point ONLY: exclusion lists are per-card and change, so check your
-- own terms and edit. card_id null means it applies to every card.
INSERT OR IGNORE INTO exclusions (id, card_id, mcc, reason, source) VALUES
  (1,  NULL, '6012', 'Financial services are excluded by most issuers', 'seed'),
  (2,  NULL, '6051', 'Quasi-cash and top-ups are excluded by most issuers', 'seed'),
  (3,  NULL, '4829', 'Money transfers are excluded by most issuers', 'seed'),
  (4,  NULL, '6300', 'Insurance premiums are commonly excluded', 'seed'),
  (5,  NULL, '9311', 'Tax payments are commonly excluded', 'seed'),
  (6,  NULL, '9399', 'Government services are commonly excluded', 'seed'),
  (7,  NULL, '9211', 'Court costs and fines are commonly excluded', 'seed'),
  (8,  NULL, '9222', 'Fines are commonly excluded', 'seed'),
  (9,  NULL, '8220', 'Education is commonly excluded', 'seed'),
  (10, NULL, '8211', 'Schools are commonly excluded', 'seed'),
  (11, NULL, '6513', 'Rental payments are commonly excluded', 'seed'),
  (12, NULL, '8398', 'Charitable donations are commonly excluded', 'seed');

-- Likely merchant codes. GUESSES, not facts: the code is set by the acquirer,
-- differs between outlets of the same brand and changes without notice. Confirm
-- one from a posted transaction and the app will trust it over these.
INSERT OR IGNORE INTO merchant_mcc (merchant, mcc, channel, source, confidence) VALUES
  ('din tai fung','5812','offline','seed','guess'),
  ('ntuc fairprice','5411','offline','seed','guess'),
  ('fairprice','5411','offline','seed','guess'),
  ('cold storage','5411','offline','seed','guess'),
  ('sheng siong','5411','offline','seed','guess'),
  ('giant','5411','offline','seed','guess'),
  ('shopee','5262','online','seed','guess'),
  ('lazada','5262','online','seed','guess'),
  ('amazon','5262','online','seed','guess'),
  ('taobao','5262','online','seed','guess'),
  ('grab','4121','online','seed','guess'),
  ('gojek','4121','online','seed','guess'),
  ('comfortdelgro','4121','offline','seed','guess'),
  ('courts','5732','offline','seed','guess'),
  ('harvey norman','5732','offline','seed','guess'),
  ('challenger','5732','offline','seed','guess'),
  ('uniqlo','5651','offline','seed','guess'),
  ('zara','5651','offline','seed','guess'),
  ('decathlon','5941','offline','seed','guess'),
  ('watsons','5912','offline','seed','guess'),
  ('guardian','5912','offline','seed','guess'),
  ('unity','5912','offline','seed','guess'),
  ('singapore airlines','4511','online','seed','guess'),
  ('scoot','4511','online','seed','guess'),
  ('agoda','4722','online','seed','guess'),
  ('booking.com','4722','online','seed','guess'),
  ('expedia','4722','online','seed','guess'),
  ('klook','4722','online','seed','guess'),
  ('netflix','4899','online','seed','guess'),
  ('spotify','4899','online','seed','guess'),
  ('disney+','4899','online','seed','guess'),
  ('singtel','4814','online','seed','guess'),
  ('starhub','4814','online','seed','guess'),
  ('m1','4814','online','seed','guess'),
  ('sp group','4900','online','seed','guess'),
  ('shell','5541','offline','seed','guess'),
  ('esso','5541','offline','seed','guess'),
  ('caltex','5541','offline','seed','guess'),
  ('spc','5541','offline','seed','guess'),
  ('golden village','7832','online','seed','guess'),
  ('cathay cineplexes','7832','offline','seed','guess'),
  ('starbucks','5814','offline','seed','guess'),
  ('mcdonald''s','5814','offline','seed','guess'),
  ('toast box','5814','offline','seed','guess'),
  ('ya kun','5814','offline','seed','guess'),
  ('kopitiam','5814','offline','seed','guess');
